// ==============================================================================
// LIVE LEADS MOCK DATA — Zélla Central Control
// ==============================================================================
// Real geolocalized Brazilian Pousadas & Airbnb Hosts across all 5 regions
// ==============================================================================

export interface LiveLead {
  id: string;
  pousada: string;
  email: string;
  whatsapp: string;
  qtdQuartos: number | null;
  localPraia: string | null;
  cidade: string;
  uf: string;
  valoresEstimados: string | null;
  qualificacao: string | null;
  validacao: 'validado' | 'pendente' | 'em_analise';
  comportamentoCompra: 'Moderno' | 'Tradicional' | 'Elite' | 'Pragmatico';
  sinaisIntencao: string | null;
  redesSociais: string | null;
  site: string | null;
  telefone: string | null;
  scoreQual: number;
  scoreValid: number;
  scoreTotal: number;
  latitude: number;
  longitude: number;
  regiao: 'Sul' | 'Sudeste' | 'Nordeste' | 'Norte' | 'Centro-Oeste';
  status: 'novo' | 'contatado' | 'respondido' | 'convertido' | 'perdido';
  funilEstagio: 'frio' | 'morno' | 'quente' | 'trial' | 'convertido';
  cluster: 'frio' | 'morno' | 'quente';
  dorIdentificada: 'financeiro' | 'operacional' | 'ocupacao' | 'desconhecida';
  ultimoContato: string;
  tipoPropriedade: 'Pousada' | 'Airbnb' | 'Hotel Boutique' | 'Resort';
}

export const MOCK_LIVE_LEADS: LiveLead[] = [
  // === SUDESTE ===
  {
    id: 'lead-01',
    pousada: 'Pousada Serenity Paraty',
    email: 'contato@serenityparaty.com.br',
    whatsapp: '5524999881122',
    qtdQuartos: 14,
    localPraia: 'Centro Histórico',
    cidade: 'Paraty',
    uf: 'RJ',
    valoresEstimados: 'R$ 450 - R$ 850',
    qualificacao: 'Pousada charme com arquitetura colonial e alta ocupação em finais de semana',
    validacao: 'validado',
    comportamentoCompra: 'Moderno',
    sinaisIntencao: 'Busca eliminar 18% de comissão Booking no WhatsApp',
    redesSociais: '@pousadaserenityparaty',
    site: 'www.serenityparaty.com.br',
    telefone: '2433711122',
    scoreQual: 94,
    scoreValid: 92,
    scoreTotal: 93,
    latitude: -23.2178,
    longitude: -44.7131,
    regiao: 'Sudeste',
    status: 'respondido',
    funilEstagio: 'quente',
    cluster: 'quente',
    dorIdentificada: 'financeiro',
    ultimoContato: '2026-08-10T19:30:00Z',
    tipoPropriedade: 'Pousada',
  },
  {
    id: 'lead-02',
    pousada: 'Villa Bella Búzios',
    email: 'reservas@villabellabuzios.com.br',
    whatsapp: '5522998765432',
    qtdQuartos: 18,
    localPraia: 'Praia de Geribá',
    cidade: 'Armação dos Búzios',
    uf: 'RJ',
    valoresEstimados: 'R$ 520 - R$ 980',
    qualificacao: 'Pousada boutique 50m da praia, foco em casais e famílias VIP',
    validacao: 'validado',
    comportamentoCompra: 'Elite',
    sinaisIntencao: 'Quer atendimento de inteligência artificial 24h sem perder elegância',
    redesSociais: '@villabellabuzios',
    site: 'www.villabellabuzios.com.br',
    telefone: '2226234455',
    scoreQual: 96,
    scoreValid: 95,
    scoreTotal: 96,
    latitude: -22.7667,
    longitude: -41.9000,
    regiao: 'Sudeste',
    status: 'convertido',
    funilEstagio: 'convertido',
    cluster: 'quente',
    dorIdentificada: 'operacional',
    ultimoContato: '2026-08-09T14:20:00Z',
    tipoPropriedade: 'Pousada',
  },
  {
    id: 'lead-03',
    pousada: 'Chalés das Montanhas Monte Verde',
    email: 'contato@chalesmonteverde.com.br',
    whatsapp: '5535997654321',
    qtdQuartos: 10,
    localPraia: 'Serra da Mantiqueira',
    cidade: 'Camanducaia',
    uf: 'MG',
    valoresEstimados: 'R$ 380 - R$ 690',
    qualificacao: 'Chalés românticos com lareira e hidromassagem',
    validacao: 'validado',
    comportamentoCompra: 'Tradicional',
    sinaisIntencao: 'Dificuldade em responder cotações no WhatsApp à noite',
    redesSociais: '@chalesmonteverde.mg',
    site: 'www.chalesmonteverde.com.br',
    telefone: '3534381122',
    scoreQual: 88,
    scoreValid: 86,
    scoreTotal: 87,
    latitude: -22.8631,
    longitude: -46.0353,
    regiao: 'Sudeste',
    status: 'contatado',
    funilEstagio: 'morno',
    cluster: 'morno',
    dorIdentificada: 'operacional',
    ultimoContato: '2026-08-10T11:15:00Z',
    tipoPropriedade: 'Pousada',
  },
  {
    id: 'lead-04',
    pousada: 'Airbnb Design Studio Moema',
    email: 'anfitriao.moema@gmail.com',
    whatsapp: '5511988776655',
    qtdQuartos: 4,
    localPraia: 'Urbano / Aeroporto Congonhas',
    cidade: 'São Paulo',
    uf: 'SP',
    valoresEstimados: 'R$ 290 - R$ 420',
    qualificacao: '4 apartamentos compactos de alto padrão para executivos e turismo de negócios',
    validacao: 'validado',
    comportamentoCompra: 'Moderno',
    sinaisIntencao: 'Deseja geração de Auto-PIN para fechadura eletrônica TTLock',
    redesSociais: '@studiosmoema.sp',
    site: null,
    telefone: '11988776655',
    scoreQual: 91,
    scoreValid: 90,
    scoreTotal: 91,
    latitude: -23.6041,
    longitude: -46.6606,
    regiao: 'Sudeste',
    status: 'respondido',
    funilEstagio: 'quente',
    cluster: 'quente',
    dorIdentificada: 'operacional',
    ultimoContato: '2026-08-10T20:45:00Z',
    tipoPropriedade: 'Airbnb',
  },
  {
    id: 'lead-05',
    pousada: 'Pousada Refúgio do Sol Ilhabela',
    email: 'info@refugiodosolilhabela.com.br',
    whatsapp: '5512996543210',
    qtdQuartos: 12,
    localPraia: 'Praia do Curral',
    cidade: 'Ilhabela',
    uf: 'SP',
    valoresEstimados: 'R$ 490 - R$ 890',
    qualificacao: 'Pousada integrada à natureza com deck panorâmico para o mar',
    validacao: 'validado',
    comportamentoCompra: 'Moderno',
    sinaisIntencao: 'Quer receber reservas direto com chave PIX instantânea',
    redesSociais: '@refugiodosolilhabela',
    site: 'www.refugiodosolilhabela.com.br',
    telefone: '1238941122',
    scoreQual: 93,
    scoreValid: 94,
    scoreTotal: 94,
    latitude: -23.8344,
    longitude: -45.4191,
    regiao: 'Sudeste',
    status: 'convertido',
    funilEstagio: 'convertido',
    cluster: 'quente',
    dorIdentificada: 'financeiro',
    ultimoContato: '2026-08-08T18:10:00Z',
    tipoPropriedade: 'Pousada',
  },

  // === SUL ===
  {
    id: 'lead-06',
    pousada: 'Pousada Flor do Sul Florianópolis',
    email: 'contato@flordosul.com.br',
    whatsapp: '5548999990004',
    qtdQuartos: 16,
    localPraia: 'Praia da Joaquina',
    cidade: 'Florianópolis',
    uf: 'SC',
    valoresEstimados: 'R$ 420 - R$ 780',
    qualificacao: 'Boutique premium com vista para o mar, público surfista e famílias',
    validacao: 'validado',
    comportamentoCompra: 'Moderno',
    sinaisIntencao: 'Implementando automação completa de atendimento via WhatsApp',
    redesSociais: '@flordosul.fln',
    site: 'www.flordosul.com.br',
    telefone: '4832220004',
    scoreQual: 95,
    scoreValid: 96,
    scoreTotal: 95,
    latitude: -27.5954,
    longitude: -48.5210,
    regiao: 'Sul',
    status: 'convertido',
    funilEstagio: 'convertido',
    cluster: 'quente',
    dorIdentificada: 'financeiro',
    ultimoContato: '2026-08-10T16:00:00Z',
    tipoPropriedade: 'Pousada',
  },
  {
    id: 'lead-07',
    pousada: 'Pousada Vale dos Vinhedos Gramado',
    email: 'reservas@pousadavaledosvinhedos.com.br',
    whatsapp: '5554991234567',
    qtdQuartos: 22,
    localPraia: 'Serra Gaúcha',
    cidade: 'Gramado',
    uf: 'RS',
    valoresEstimados: 'R$ 650 - R$ 1400',
    qualificacao: 'Pousada 5 estrelas na serra gaúcha com adega e café colonial exclusivo',
    validacao: 'validado',
    comportamentoCompra: 'Elite',
    sinaisIntencao: 'Busca solução sem comissão para pacotes de inverno',
    redesSociais: '@pousadavaledosvinhedos',
    site: 'www.pousadavaledosvinhedos.com.br',
    telefone: '5432861122',
    scoreQual: 97,
    scoreValid: 95,
    scoreTotal: 96,
    latitude: -29.3788,
    longitude: -50.8739,
    regiao: 'Sul',
    status: 'respondido',
    funilEstagio: 'quente',
    cluster: 'quente',
    dorIdentificada: 'financeiro',
    ultimoContato: '2026-08-10T21:00:00Z',
    tipoPropriedade: 'Pousada',
  },
  {
    id: 'lead-08',
    pousada: 'Pousada Encanto da Serra Morretes',
    email: 'reservas@encantoserra.com.br',
    whatsapp: '5542999990002',
    qtdQuartos: 8,
    localPraia: 'Serra do Mar',
    cidade: 'Morretes',
    uf: 'PR',
    valoresEstimados: 'R$ 320 - R$ 580',
    qualificacao: 'Eco-luxury na Serra do Mar, experiência gastronômica com barreado',
    validacao: 'validado',
    comportamentoCompra: 'Elite',
    sinaisIntencao: 'Quer reduzir dependência do Booking em 90%',
    redesSociais: '@encantoserra.pr',
    site: 'www.encantoserra.com.br',
    telefone: '4134440002',
    scoreQual: 92,
    scoreValid: 88,
    scoreTotal: 90,
    latitude: -25.4953,
    longitude: -48.8756,
    regiao: 'Sul',
    status: 'contatado',
    funilEstagio: 'morno',
    cluster: 'morno',
    dorIdentificada: 'financeiro',
    ultimoContato: '2026-08-09T17:40:00Z',
    tipoPropriedade: 'Pousada',
  },

  // === NORDESTE ===
  {
    id: 'lead-09',
    pousada: 'Pousada Rota dos Milagres',
    email: 'contato@rotadosmilagres.com.br',
    whatsapp: '5582998112233',
    qtdQuartos: 15,
    localPraia: 'São Miguel dos Milagres',
    cidade: 'São Miguel dos Milagres',
    uf: 'AL',
    valoresEstimados: 'R$ 790 - R$ 1600',
    qualificacao: 'Bangalôs sobre as águas cristalinas de Milagres, público réveillon e noivas',
    validacao: 'validado',
    comportamentoCompra: 'Elite',
    sinaisIntencao: 'Quer checkout 24h e envio de contrato de hospedagem digital',
    redesSociais: '@pousadadeluxe.milagres',
    site: 'www.rotadosmilagres.com.br',
    telefone: '8232981122',
    scoreQual: 98,
    scoreValid: 97,
    scoreTotal: 97,
    latitude: -9.2625,
    longitude: -35.3736,
    regiao: 'Nordeste',
    status: 'respondido',
    funilEstagio: 'quente',
    cluster: 'quente',
    dorIdentificada: 'ocupacao',
    ultimoContato: '2026-08-10T18:50:00Z',
    tipoPropriedade: 'Pousada',
  },
  {
    id: 'lead-10',
    pousada: 'Pousada Jeri Wind Paradise',
    email: 'reservas@jeriwindparadise.com.br',
    whatsapp: '5588997651122',
    qtdQuartos: 20,
    localPraia: 'Praia Principal / Duna do Pôr do Sol',
    cidade: 'Jijoca de Jericoacoara',
    uf: 'CE',
    valoresEstimados: 'R$ 580 - R$ 1100',
    qualificacao: 'Pousada esportiva especializada em praticantes de Kitesurf do mundo inteiro',
    validacao: 'validado',
    comportamentoCompra: 'Moderno',
    sinaisIntencao: 'Atendimento bilíngue automático no WhatsApp',
    redesSociais: '@jeriwindparadise',
    site: 'www.jeriwindparadise.com.br',
    telefone: '8836691122',
    scoreQual: 94,
    scoreValid: 91,
    scoreTotal: 92,
    latitude: -2.7972,
    longitude: -40.5139,
    regiao: 'Nordeste',
    status: 'novo',
    funilEstagio: 'morno',
    cluster: 'morno',
    dorIdentificada: 'operacional',
    ultimoContato: '2026-08-10T12:00:00Z',
    tipoPropriedade: 'Pousada',
  },
  {
    id: 'lead-11',
    pousada: 'Pousada Vila das Cores Pipa',
    email: 'contato@viladascorespipa.com.br',
    whatsapp: '5584996443322',
    qtdQuartos: 11,
    localPraia: 'Praia do Amor',
    cidade: 'Tibau do Sul',
    uf: 'RN',
    valoresEstimados: 'R$ 390 - R$ 720',
    qualificacao: 'Pousada alto astral com piscina de pedras vulcânicas e jardim tropical',
    validacao: 'validado',
    comportamentoCompra: 'Pragmatico',
    sinaisIntencao: 'Interesse imediato em substituir taxa do Airbnb por PIX no WhatsApp',
    redesSociais: '@viladascorespipa',
    site: 'www.viladascorespipa.com.br',
    telefone: '8432461122',
    scoreQual: 89,
    scoreValid: 87,
    scoreTotal: 88,
    latitude: -6.2306,
    longitude: -35.0458,
    regiao: 'Nordeste',
    status: 'contatado',
    funilEstagio: 'morno',
    cluster: 'morno',
    dorIdentificada: 'financeiro',
    ultimoContato: '2026-08-10T14:10:00Z',
    tipoPropriedade: 'Pousada',
  },

  // === CENTRO-OESTE ===
  {
    id: 'lead-12',
    pousada: 'Pousada Águas de Pirenópolis',
    email: 'contato@aguasdepirenopolis.com.br',
    whatsapp: '5562991122334',
    qtdQuartos: 16,
    localPraia: 'Centro Histórico / Cachoeiras',
    cidade: 'Pirenópolis',
    uf: 'GO',
    valoresEstimados: 'R$ 350 - R$ 680',
    qualificacao: 'Pousada com piscinas aquecidas e ampla área verde próximo às cachoeiras',
    validacao: 'validado',
    comportamentoCompra: 'Tradicional',
    sinaisIntencao: 'Sobrecarga de dúvidas de reservas nos fins de semana',
    redesSociais: '@pousadadepirenopolis',
    site: 'www.aguasdepirenopolis.com.br',
    telefone: '6233311122',
    scoreQual: 86,
    scoreValid: 84,
    scoreTotal: 85,
    latitude: -15.8525,
    longitude: -48.9592,
    regiao: 'Centro-Oeste',
    status: 'respondido',
    funilEstagio: 'quente',
    cluster: 'morno',
    dorIdentificada: 'operacional',
    ultimoContato: '2026-08-10T17:25:00Z',
    tipoPropriedade: 'Pousada',
  },
  {
    id: 'lead-13',
    pousada: 'Ecolodge Bonito Pantanal',
    email: 'reservas@ecolodgebonito.com.br',
    whatsapp: '5567998877112',
    qtdQuartos: 14,
    localPraia: 'Rio Sucuri',
    cidade: 'Bonito',
    uf: 'MS',
    valoresEstimados: 'R$ 620 - R$ 1250',
    qualificacao: 'Ecolodge sustentável focado em ecoturismo, flutuação e mergulho',
    validacao: 'validado',
    comportamentoCompra: 'Elite',
    sinaisIntencao: 'Automação de informações de passeios e reservas diretas',
    redesSociais: '@ecolodgebonitoms',
    site: 'www.ecolodgebonito.com.br',
    telefone: '6732551122',
    scoreQual: 93,
    scoreValid: 91,
    scoreTotal: 92,
    latitude: -21.1264,
    longitude: -56.4836,
    regiao: 'Centro-Oeste',
    status: 'novo',
    funilEstagio: 'frio',
    cluster: 'morno',
    dorIdentificada: 'ocupacao',
    ultimoContato: '2026-08-10T09:30:00Z',
    tipoPropriedade: 'Hotel Boutique',
  },

  // === NORTE ===
  {
    id: 'lead-14',
    pousada: 'Pousada Alter do Chão Amazônia',
    email: 'contato@alteramazonia.com.br',
    whatsapp: '5593992233445',
    qtdQuartos: 10,
    localPraia: 'Praia do Amor / Rio Tapajós',
    cidade: 'Santarém',
    uf: 'PA',
    valoresEstimados: 'R$ 410 - R$ 790',
    qualificacao: 'Pousada rústica-chic nas praias de água doce de Alter do Chão',
    validacao: 'validado',
    comportamentoCompra: 'Moderno',
    sinaisIntencao: 'Falta de canal rápido de vendas via PIX para gringos e turistas de SP',
    redesSociais: '@alterdochao.pousada',
    site: 'www.alteramazonia.com.br',
    telefone: '9335221122',
    scoreQual: 90,
    scoreValid: 89,
    scoreTotal: 90,
    latitude: -2.4431,
    longitude: -54.9547,
    regiao: 'Norte',
    status: 'respondido',
    funilEstagio: 'quente',
    cluster: 'quente',
    dorIdentificada: 'financeiro',
    ultimoContato: '2026-08-10T15:40:00Z',
    tipoPropriedade: 'Pousada',
  },
  {
    id: 'lead-15',
    pousada: 'Jungle Lodge Encontro das Águas',
    email: 'reservas@junglelodgemanauara.com.br',
    whatsapp: '5592998811990',
    qtdQuartos: 18,
    localPraia: 'Rio Negro',
    cidade: 'Manaus',
    uf: 'AM',
    valoresEstimados: 'R$ 890 - R$ 1800',
    qualificacao: 'Hotel de selva com bangalôs flutuantes no Rio Negro',
    validacao: 'validado',
    comportamentoCompra: 'Elite',
    sinaisIntencao: 'Aumentar taxa de conversão direta sem repassar comissão de OTA',
    redesSociais: '@junglelodge.am',
    site: 'www.junglelodgemanauara.com.br',
    telefone: '9236551122',
    scoreQual: 96,
    scoreValid: 94,
    scoreTotal: 95,
    latitude: -3.1190,
    longitude: -60.0217,
    regiao: 'Norte',
    status: 'convertido',
    funilEstagio: 'convertido',
    cluster: 'quente',
    dorIdentificada: 'financeiro',
    ultimoContato: '2026-08-07T13:20:00Z',
    tipoPropriedade: 'Resort',
  },
];

export interface LiveLeadsStats {
  totalLeads: number;
  avgScoreQual: number;
  avgScoreValid: number;
  totalVendasEstimadas: string;
  regioes: { regiao: string; count: number; pct: number }[];
  statusList: { status: string; count: number; label: string }[];
  topUfs: { uf: string; count: number }[];
}

export function getMockStats(leads: LiveLead[] = MOCK_LIVE_LEADS): LiveLeadsStats {
  const total = leads.length;
  const avgQual = Math.round(leads.reduce((acc, l) => acc + l.scoreQual, 0) / total);
  const avgValid = Math.round(leads.reduce((acc, l) => acc + l.scoreValid, 0) / total);

  // Group by region
  const regMap: Record<string, number> = {};
  leads.forEach((l) => {
    regMap[l.regiao] = (regMap[l.regiao] || 0) + 1;
  });
  const regioes = Object.entries(regMap).map(([regiao, count]) => ({
    regiao,
    count,
    pct: Math.round((count / total) * 100),
  }));

  // Group by status
  const statMap: Record<string, number> = {};
  leads.forEach((l) => {
    statMap[l.status] = (statMap[l.status] || 0) + 1;
  });
  const statusLabels: Record<string, string> = {
    novo: 'Novo Lead',
    contatado: 'Contatado',
    respondido: 'Em Negociação',
    convertido: 'Cliente Zélla',
    perdido: 'Perdido',
  };
  const statusList = Object.entries(statMap).map(([status, count]) => ({
    status,
    count,
    label: statusLabels[status] || status,
  }));

  // Group by UF
  const ufMap: Record<string, number> = {};
  leads.forEach((l) => {
    ufMap[l.uf] = (ufMap[l.uf] || 0) + 1;
  });
  const topUfs = Object.entries(ufMap)
    .map(([uf, count]) => ({ uf, count }))
    .sort((a, b) => b.count - a.count);

  return {
    totalLeads: total,
    avgScoreQual: avgQual,
    avgScoreValid: avgValid,
    totalVendasEstimadas: 'R$ 142.800/mês',
    regioes,
    statusList,
    topUfs,
  };
}
