/**
 * MOCK DATA — ZCC
 * 37 pousadas reais geolocalizadas em todas as 5 regiões do Brasil.
 * Dados extraídos de scripts/seed-leads.ts do projeto Seu Zélla.
 * Para dados reais: chame a API /api/leads (Prisma).
 */

import type {
  Lead,
  Agent,
  Integration,
  BrainEvent,
  OperatorKPI,
  LeadsStats,
  ActivityEntry,
} from "./types";

const now = new Date();
const hoursAgo = (h: number) => {
  const d = new Date(now);
  d.setHours(d.getHours() - h);
  return d.toISOString();
};

// ============================================================================
// 37 LEADS — pousadas reais geolocalizadas
// ============================================================================

export const leads: Lead[] = [
  {
    id: "seed-matinhos-vida",
    pousada: "Pousada Vida Sol e Mar",
    email: "contato@vidasolemar.com.br",
    whatsapp: "5541999990001",
    qtdQuartos: 12,
    localPraia: "Praia de Matinhos",
    cidade: "Matinhos",
    uf: "PR",
    valoresEstimados: "R$ 250 - R$ 450",
    qualificacao: "Pousada boutique à beira-mar com café da manhã artesanal",
    validacao: "validado",
    comportamentoCompra: "Tradicional",
    sinaisIntencao: "Busca sistema de reservas online",
    redesSociais: "@vidasolemar",
    site: "www.vidasolemar.com.br",
    telefone: "4133330001",
    scoreQual: 85,
    scoreValid: 92,
    latitude: -25.8164,
    longitude: -48.5417,
    regiao: "Sul",
    status: "contatado",
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(3),
  },
  {
    id: "seed-morretes-encanto",
    pousada: "Pousada Encanto da Serra",
    email: "reservas@encantoserra.com.br",
    whatsapp: "5542999990002",
    qtdQuartos: 8,
    localPraia: "Morretes - Serra do Mar",
    cidade: "Morretes",
    uf: "PR",
    valoresEstimados: "R$ 320 - R$ 580",
    qualificacao: "Eco-luxury na Serra do Mar, experiência gastronômica",
    validacao: "validado",
    comportamentoCompra: "Elite",
    sinaisIntencao: "Quer reduzir comissao do Booking",
    redesSociais: "@encantoserra.pr",
    site: "www.encantoserra.com.br",
    telefone: "4134440002",
    scoreQual: 92,
    scoreValid: 88,
    latitude: -25.4953,
    longitude: -48.8756,
    regiao: "Sul",
    status: "respondido",
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
  },
  {
    id: "seed-paranaguá-ilha",
    pousada: "Pousada Ilha do Mel",
    email: "pousada@ilhadomel.com.br",
    whatsapp: "5541999990003",
    qtdQuartos: 6,
    localPraia: "Ilha do Mel",
    cidade: "Paranaguá",
    uf: "PR",
    valoresEstimados: "R$ 180 - R$ 350",
    qualificacao: "Pousada rústica-charmosa, acesso apenas por barco",
    validacao: "validado",
    comportamentoCompra: "Tradicional",
    sinaisIntencao: "Nenhuma urgência detectada",
    redesSociais: "@ilhadomel.pousada",
    telefone: "4134220003",
    scoreQual: 68,
    scoreValid: 75,
    latitude: -25.5483,
    longitude: -48.3472,
    regiao: "Sul",
    status: "novo",
    createdAt: hoursAgo(9),
    updatedAt: hoursAgo(9),
  },
  {
    id: "seed-florianopolis-boutique",
    pousada: "Hotel Boutique Flor do Sul",
    email: "contato@flordosul.com.br",
    whatsapp: "5548999990004",
    qtdQuartos: 15,
    localPraia: "Praia da Joaquina",
    cidade: "Florianópolis",
    uf: "SC",
    valoresEstimados: "R$ 400 - R$ 750",
    qualificacao: "Boutique premium com vista para o mar, design contemporâneo",
    validacao: "validado",
    comportamentoCompra: "Moderno",
    sinaisIntencao: "Implementando automação de WhatsApp",
    redesSociais: "@flordosul.fln",
    site: "www.flordosul.com.br",
    telefone: "4832220004",
    scoreQual: 95,
    scoreValid: 96,
    latitude: -27.5954,
    longitude: -48.521,
    regiao: "Sul",
    status: "convertido",
    createdAt: hoursAgo(12),
    updatedAt: hoursAgo(12),
  },
  {
    id: "seed-imbituba-vila",
    pousada: "Pousada Vila Tamarindo",
    email: "reservas@vilatamarindo.com.br",
    whatsapp: "5547999990005",
    qtdQuartos: 10,
    localPraia: "Praia do Rosa",
    cidade: "Imbituba",
    uf: "SC",
    valoresEstimados: "R$ 350 - R$ 600",
    qualificacao: "Charmosa pousada na Praia do Rosa, foco em surf e natureza",
    validacao: "validado",
    comportamentoCompra: "Moderno",
    sinaisIntencao: "Trauma com comissão alta de OTAs",
    redesSociais: "@vilatamarindo.imb",
    site: "www.vilatamarindo.com.br",
    telefone: "4733330005",
    scoreQual: 88,
    scoreValid: 90,
    latitude: -28.4478,
    longitude: -48.6678,
    regiao: "Sul",
    status: "contatado",
    createdAt: hoursAgo(15),
    updatedAt: hoursAgo(15),
  },
  {
    id: "seed-torres-costa",
    pousada: "Pousada Costa Verde Torres",
    email: "info@costaverdetorres.com.br",
    whatsapp: "5551999990006",
    qtdQuartos: 9,
    localPraia: "Praia da Guarita",
    cidade: "Torres",
    uf: "RS",
    valoresEstimados: "R$ 200 - R$ 380",
    qualificacao: "Pousada familiar com acesso direto à praia",
    validacao: "pendente",
    comportamentoCompra: "Tradicional",
    sinaisIntencao: "Buscando sistema de gestão",
    redesSociais: "@costaverde.torres",
    telefone: "5136260006",
    scoreQual: 72,
    scoreValid: 55,
    latitude: -29.3347,
    longitude: -49.7275,
    regiao: "Sul",
    status: "novo",
    createdAt: hoursAgo(18),
    updatedAt: hoursAgo(18),
  },
  {
    id: "seed-canela-serra",
    pousada: "Pousada Serra Gaúcha Charm",
    email: "pousada@serragaucha.com.br",
    whatsapp: "5554999990007",
    qtdQuartos: 14,
    localPraia: "Centro de Canela",
    cidade: "Canela",
    uf: "RS",
    valoresEstimados: "R$ 300 - R$ 550",
    qualificacao: "Eco-charm na Serra Gaúcha, vinho e chocolate artesanal",
    validacao: "validado",
    comportamentoCompra: "Elite",
    sinaisIntencao: "Quer modernizar o atendimento digital",
    redesSociais: "@serragauchacharm",
    site: "www.serragauchacharm.com.br",
    telefone: "5435220007",
    scoreQual: 90,
    scoreValid: 85,
    latitude: -29.3622,
    longitude: -50.8139,
    regiao: "Sul",
    status: "respondido",
    createdAt: hoursAgo(21),
    updatedAt: hoursAgo(21),
  },
  {
    id: "seed-porto-belo-porto",
    pousada: "Pousada Porto Belo Retreat",
    email: "reservas@portobeloretreat.com.br",
    whatsapp: "5547999990008",
    qtdQuartos: 7,
    localPraia: "Praia de Porto Belo",
    cidade: "Porto Belo",
    uf: "SC",
    valoresEstimados: "R$ 280 - R$ 500",
    qualificacao: "Retiro exclusivo com spa e gastronomia premium",
    validacao: "validado",
    comportamentoCompra: "Elite",
    sinaisIntencao: "Interesse em IA para atendimento ao hóspede",
    redesSociais: "@portobeloretreat",
    site: "www.portobeloretreat.com.br",
    telefone: "4733620008",
    scoreQual: 87,
    scoreValid: 91,
    latitude: -27.1406,
    longitude: -48.5436,
    regiao: "Sul",
    status: "contatado",
    createdAt: hoursAgo(24),
    updatedAt: hoursAgo(24),
  },
  {
    id: "seed-armacao-dos-buzios-mar",
    pousada: "Pousada Mar e Terra Búzios",
    email: "contato@mareterrabuzios.com.br",
    whatsapp: "5522999990010",
    qtdQuartos: 18,
    localPraia: "Rua das Pedras - Búzios",
    cidade: "Armação dos Búzios",
    uf: "RJ",
    valoresEstimados: "R$ 450 - R$ 800",
    qualificacao: "Premium location, vista panorâmica, foco em casais",
    validacao: "validado",
    comportamentoCompra: "Elite",
    sinaisIntencao: "Quer automação de check-in e WhatsApp",
    redesSociais: "@mareterrabuzios",
    site: "www.mareterrabuzios.com.br",
    telefone: "2226230010",
    scoreQual: 96,
    scoreValid: 98,
    latitude: -22.7469,
    longitude: -41.8817,
    regiao: "Sudeste",
    status: "convertido",
    createdAt: hoursAgo(27),
    updatedAt: hoursAgo(27),
  },
  {
    id: "seed-paraty-raio",
    pousada: "Pousada Raio de Sol Paraty",
    email: "reservas@raiodesol.com.br",
    whatsapp: "5524999990011",
    qtdQuartos: 11,
    localPraia: "Centro Histórico",
    cidade: "Paraty",
    uf: "RJ",
    valoresEstimados: "R$ 350 - R$ 600",
    qualificacao: "Casa colonial restaurada, charme histórico",
    validacao: "validado",
    comportamentoCompra: "Tradicional",
    sinaisIntencao: "Dificuldade com revenue management",
    redesSociais: "@raiodesolparaty",
    site: "www.raiodesolparaty.com.br",
    telefone: "2433710011",
    scoreQual: 82,
    scoreValid: 87,
    latitude: -23.2178,
    longitude: -44.7131,
    regiao: "Sudeste",
    status: "contatado",
    createdAt: hoursAgo(30),
    updatedAt: hoursAgo(30),
  },
  {
    id: "seed-paraty-sitio",
    pousada: "Pousada Sítio da Lua Trindade",
    email: "sitiodalua@gmail.com",
    whatsapp: "5524999990012",
    qtdQuartos: 5,
    localPraia: "Praia do Rancho",
    cidade: "Paraty",
    uf: "RJ",
    valoresEstimados: "R$ 200 - R$ 380",
    qualificacao: "Rural-charm, cachoeira privativa, experiência imersiva",
    validacao: "validado",
    comportamentoCompra: "Tradicional",
    sinaisIntencao: "Nenhuma urgência",
    redesSociais: "@sitiodalua.trindade",
    telefone: "2433720012",
    scoreQual: 70,
    scoreValid: 65,
    latitude: -23.1025,
    longitude: -44.695,
    regiao: "Sudeste",
    status: "novo",
    createdAt: hoursAgo(33),
    updatedAt: hoursAgo(33),
  },
  {
    id: "seed-arraial-do-cabo-canto",
    pousada: "Pousada Canto do Mar Arraial",
    email: "reservas@cantodomar.com.br",
    whatsapp: "5522999990013",
    qtdQuartos: 13,
    localPraia: "Praia dos Anjos",
    cidade: "Arraial do Cabo",
    uf: "RJ",
    valoresEstimados: "R$ 300 - R$ 520",
    qualificacao: "Beira-mar com mergulho, foco em ecoturismo",
    validacao: "validado",
    comportamentoCompra: "Moderno",
    sinaisIntencao: "Precisa de sistema de reservas online",
    redesSociais: "@cantodomar.arr",
    site: "www.cantodomar.com.br",
    telefone: "2226390013",
    scoreQual: 84,
    scoreValid: 80,
    latitude: -22.9664,
    longitude: -42.0272,
    regiao: "Sudeste",
    status: "contatado",
    createdAt: hoursAgo(36),
    updatedAt: hoursAgo(36),
  },
  {
    id: "seed-ilhabela-refugio",
    pousada: "Pousada Refúgio da Praia Ilhabela",
    email: "contato@refugiodapraia.com.br",
    whatsapp: "5512999990014",
    qtdQuartos: 9,
    localPraia: "Praia da Julieta",
    cidade: "Ilhabela",
    uf: "SP",
    valoresEstimados: "R$ 380 - R$ 650",
    qualificacao: "Pousada boutique isolada, acesso por trilha ou barco",
    validacao: "validado",
    comportamentoCompra: "Elite",
    sinaisIntencao: "Busca plataforma zero-comissão",
    redesSociais: "@refugiodapraia.ilhabela",
    site: "www.refugiodapraia.com.br",
    telefone: "1238920014",
    scoreQual: 91,
    scoreValid: 93,
    latitude: -23.8197,
    longitude: -45.3461,
    regiao: "Sudeste",
    status: "respondido",
    createdAt: hoursAgo(39),
    updatedAt: hoursAgo(39),
  },
  {
    id: "seed-ubatuba-pe",
    pousada: "Pousada Pé na Areia Ubatuba",
    email: "pousada@penaareia.com.br",
    whatsapp: "5512999990015",
    qtdQuartos: 16,
    localPraia: "Praia do Lázaro",
    cidade: "Ubatuba",
    uf: "SP",
    valoresEstimados: "R$ 250 - R$ 450",
    qualificacao: "Familiar, localização privilegiada, piscina natural",
    validacao: "validado",
    comportamentoCompra: "Tradicional",
    sinaisIntencao: "Precisa de gestão de diárias e canais",
    redesSociais: "@penaareia.ubatuba",
    site: "www.penaareia.com.br",
    telefone: "1238330015",
    scoreQual: 78,
    scoreValid: 82,
    latitude: -23.4361,
    longitude: -45.0833,
    regiao: "Sudeste",
    status: "novo",
    createdAt: hoursAgo(42),
    updatedAt: hoursAgo(42),
  },
  {
    id: "seed-monte-siao-boutique",
    pousada: "Pousada Boutique Serra da Mantiqueira",
    email: "contato@serramantiqueira.com.br",
    whatsapp: "5535999990016",
    qtdQuartos: 20,
    localPraia: "Monte Sião",
    cidade: "Monte Sião",
    uf: "MG",
    valoresEstimados: "R$ 280 - R$ 500",
    qualificacao: "Mountain lodge premium, cafeicultura e trilhas",
    validacao: "validado",
    comportamentoCompra: "Moderno",
    sinaisIntencao: "Quer automatizar comunicação com hóspedes",
    redesSociais: "@serramantiqueira.mg",
    site: "www.serramantiqueira.com.br",
    telefone: "3535610016",
    scoreQual: 86,
    scoreValid: 88,
    latitude: -22.3994,
    longitude: -46.5789,
    regiao: "Sudeste",
    status: "contatado",
    createdAt: hoursAgo(45),
    updatedAt: hoursAgo(45),
  },
  {
    id: "seed-ouro-preto-ouro",
    pousada: "Pousada Ouro Preto Historical",
    email: "reservas@ouropretohistorical.com.br",
    whatsapp: "5531999990017",
    qtdQuartos: 10,
    localPraia: "Centro Histórico",
    cidade: "Ouro Preto",
    uf: "MG",
    valoresEstimados: "R$ 220 - R$ 400",
    qualificacao: "Casa colonial com decoração antiga e gastronomia mineira",
    validacao: "validado",
    comportamentoCompra: "Tradicional",
    sinaisIntencao: "Baixa presença digital, busca aumento de reservas diretas",
    redesSociais: "@ouropretohistorical",
    site: "www.ouropretohistorical.com.br",
    telefone: "3135590017",
    scoreQual: 74,
    scoreValid: 70,
    latitude: -20.3856,
    longitude: -43.5033,
    regiao: "Sudeste",
    status: "novo",
    createdAt: hoursAgo(48),
    updatedAt: hoursAgo(48),
  },
  {
    id: "seed-alto-caparao-caparao",
    pousada: "Pousada Caparao Eco Lodge",
    email: "eco@caparaolodge.com.br",
    whatsapp: "5528999990018",
    qtdQuartos: 8,
    localPraia: "Parque Nacional do Caparaó",
    cidade: "Alto Caparaó",
    uf: "MG",
    valoresEstimados: "R$ 200 - R$ 350",
    qualificacao: "Eco-lodge com vista para o Pico da Bandeira",
    validacao: "validado",
    comportamentoCompra: "Moderno",
    sinaisIntencao: "Interesse em marketing digital",
    redesSociais: "@caparaoecolodge",
    site: "www.caparaoecolodge.com.br",
    telefone: "2835720018",
    scoreQual: 80,
    scoreValid: 76,
    latitude: -20.3181,
    longitude: -41.8725,
    regiao: "Sudeste",
    status: "contatado",
    createdAt: hoursAgo(51),
    updatedAt: hoursAgo(51),
  },
  {
    id: "seed-serra-maravilha",
    pousada: "Pousada Maravilha Capixaba",
    email: "info@maravilhacapixaba.com.br",
    whatsapp: "5527999990019",
    qtdQuartos: 12,
    localPraia: "Praia de Camburi",
    cidade: "Serra",
    uf: "ES",
    valoresEstimados: "R$ 320 - R$ 550",
    qualificacao: "Boutique beira-mar com arquitetura contemporânea",
    validacao: "validado",
    comportamentoCompra: "Moderno",
    sinaisIntencao: "Implementando WhatsApp Business API",
    redesSociais: "@maravilhacapixaba",
    site: "www.maravilhacapixaba.com.br",
    telefone: "2733380019",
    scoreQual: 89,
    scoreValid: 92,
    latitude: -20.1272,
    longitude: -40.3047,
    regiao: "Sudeste",
    status: "respondido",
    createdAt: hoursAgo(54),
    updatedAt: hoursAgo(54),
  },
  {
    id: "seed-tiradentes-convento",
    pousada: "Pousada Convento Tiradentes",
    email: "reservas@conventotiradentes.com.br",
    whatsapp: "5532999990020",
    qtdQuartos: 15,
    localPraia: "Centro Histórico",
    cidade: "Tiradentes",
    uf: "MG",
    valoresEstimados: "R$ 400 - R$ 700",
    qualificacao: "Convento colonial transformado em pousada luxury",
    validacao: "validado",
    comportamentoCompra: "Elite",
    sinaisIntencao: "Busca integração com canais de distribuição",
    redesSociais: "@conventotiradentes",
    site: "www.conventotiradentes.com.br",
    telefone: "3235520020",
    scoreQual: 94,
    scoreValid: 95,
    latitude: -21.1192,
    longitude: -44.1847,
    regiao: "Sudeste",
    status: "convertido",
    createdAt: hoursAgo(57),
    updatedAt: hoursAgo(57),
  },
  {
    id: "seed-morro-de-sao-paulo-bahia",
    pousada: "Pousada Bahia Sol e Lua",
    email: "contato@bahiasolelua.com.br",
    whatsapp: "5571999990030",
    qtdQuartos: 14,
    localPraia: "Praia do Farol",
    cidade: "Morro de São Paulo",
    uf: "BA",
    valoresEstimados: "R$ 350 - R$ 600",
    qualificacao: "Pousada charmosa na ilha, sunset view",
    validacao: "validado",
    comportamentoCompra: "Tradicional",
    sinaisIntencao: "Perde reservas por falta de sistema online",
    redesSociais: "@bahiasolelua",
    site: "www.bahiasolelua.com.br",
    telefone: "7536530030",
    scoreQual: 83,
    scoreValid: 78,
    latitude: -13.4467,
    longitude: -38.9333,
    regiao: "Nordeste",
    status: "contatado",
    createdAt: hoursAgo(60),
    updatedAt: hoursAgo(60),
  },
  {
    id: "seed-porto-seguro-maravilha",
    pousada: "Pousada Maravilha Porto Seguro",
    email: "reservas@maravilhaps.com.br",
    whatsapp: "5573999990031",
    qtdQuartos: 22,
    localPraia: "Praia de Taperapuã",
    cidade: "Porto Seguro",
    uf: "BA",
    valoresEstimados: "R$ 250 - R$ 480",
    qualificacao: "Resort boutique com praia privativa e club infantil",
    validacao: "validado",
    comportamentoCompra: "Moderno",
    sinaisIntencao: "Quer IA para atendimento ao hóspede",
    redesSociais: "@maravilhaps",
    site: "www.maravilhaps.com.br",
    telefone: "7336880031",
    scoreQual: 88,
    scoreValid: 85,
    latitude: -16.4439,
    longitude: -39.0658,
    regiao: "Nordeste",
    status: "contatado",
    createdAt: hoursAgo(63),
    updatedAt: hoursAgo(63),
  },
  {
    id: "seed-itacare-convento",
    pousada: "Pousada Convento da Praia Itacaré",
    email: "contato@conventoitacare.com.br",
    whatsapp: "5573999990032",
    qtdQuartos: 8,
    localPraia: "Praia da Concha",
    cidade: "Itacaré",
    uf: "BA",
    valoresEstimados: "R$ 280 - R$ 500",
    qualificacao: "Charm na mata atlântica, surf e yoga",
    validacao: "validado",
    comportamentoCompra: "Moderno",
    sinaisIntencao: "Migrando de planilhas para sistema digital",
    redesSociais: "@conventoitacare",
    site: "www.conventoitacare.com.br",
    telefone: "7332520032",
    scoreQual: 85,
    scoreValid: 80,
    latitude: -14.2825,
    longitude: -38.9722,
    regiao: "Nordeste",
    status: "respondido",
    createdAt: hoursAgo(66),
    updatedAt: hoursAgo(66),
  },
  {
    id: "seed-jijoca-de-jericoacoara-praia",
    pousada: "Pousada Praia Dourada Jeri",
    email: "reservas@praiadouradajeri.com.br",
    whatsapp: "5588999990033",
    qtdQuartos: 11,
    localPraia: "Praia do Malhado",
    cidade: "Jijoca de Jericoacoara",
    uf: "CE",
    valoresEstimados: "R$ 380 - R$ 650",
    qualificacao: "Design premium, buggy tour, pôr do sol emblemático",
    validacao: "validado",
    comportamentoCompra: "Elite",
    sinaisIntencao: "Quer reduzir 100% das reservas por OTA",
    redesSociais: "@praiadouradajeri",
    site: "www.praiadouradajeri.com.br",
    telefone: "8836610033",
    scoreQual: 93,
    scoreValid: 94,
    latitude: -2.7989,
    longitude: -40.5136,
    regiao: "Nordeste",
    status: "contatado",
    createdAt: hoursAgo(69),
    updatedAt: hoursAgo(69),
  },
  {
    id: "seed-aracati-canoa",
    pousada: "Pousada Canoa Quebrada Village",
    email: "info@canoavillage.com.br",
    whatsapp: "5588999990034",
    qtdQuartos: 16,
    localPraia: "Broadwalk",
    cidade: "Aracati",
    uf: "CE",
    valoresEstimados: "R$ 220 - R$ 420",
    qualificacao: "Village estilo rústico-charmoso na falésia",
    validacao: "validado",
    comportamentoCompra: "Tradicional",
    sinaisIntencao: "Precisa de site e reservas online",
    redesSociais: "@canoavillage",
    telefone: "8834210034",
    scoreQual: 76,
    scoreValid: 72,
    latitude: -4.4494,
    longitude: -37.7803,
    regiao: "Nordeste",
    status: "novo",
    createdAt: hoursAgo(72),
    updatedAt: hoursAgo(72),
  },
  {
    id: "seed-tibau-do-sul-beleza",
    pousada: "Pousada Beleza Natural Pipa",
    email: "contato@belezanaturalpipa.com.br",
    whatsapp: "5584999990035",
    qtdQuartos: 13,
    localPraia: "Praia do Amor",
    cidade: "Tibau do Sul",
    uf: "RN",
    valoresEstimados: "R$ 350 - R$ 580",
    qualificacao: "Ocean view, accessível, surf e golfinhos",
    validacao: "validado",
    comportamentoCompra: "Moderno",
    sinaisIntencao: "Já usa WhatsApp mas quer automação",
    redesSociais: "@belezanaturalpipa",
    site: "www.belezanaturalpipa.com.br",
    telefone: "8432460035",
    scoreQual: 86,
    scoreValid: 89,
    latitude: -6.2292,
    longitude: -35.0817,
    regiao: "Nordeste",
    status: "contatado",
    createdAt: hoursAgo(75),
    updatedAt: hoursAgo(75),
  },
  {
    id: "seed-maragogi-maragogi",
    pousada: "Pousada Maragogi Exclusive",
    email: "reservas@maragogiexclusive.com.br",
    whatsapp: "5582999990036",
    qtdQuartos: 18,
    localPraia: "Praia de Maragogi",
    cidade: "Maragogi",
    uf: "AL",
    valoresEstimados: "R$ 300 - R$ 550",
    qualificacao: "Galés naturais, all-inclusive opcional, família",
    validacao: "validado",
    comportamentoCompra: "Moderno",
    sinaisIntencao: "Quer integração com Instagram e WhatsApp",
    redesSociais: "@maragogiexclusive",
    site: "www.maragogiexclusive.com.br",
    telefone: "8235530036",
    scoreQual: 87,
    scoreValid: 86,
    latitude: -9.0033,
    longitude: -35.2081,
    regiao: "Nordeste",
    status: "respondido",
    createdAt: hoursAgo(78),
    updatedAt: hoursAgo(78),
  },
  {
    id: "seed-ipojuca-porto",
    pousada: "Pousada Porto de Galinhas Gold",
    email: "contato@pdggold.com.br",
    whatsapp: "5581999990037",
    qtdQuartos: 20,
    localPraia: "Praia de Porto de Galinhas",
    cidade: "Ipojuca",
    uf: "PE",
    valoresEstimados: "R$ 400 - R$ 700",
    qualificacao: "Premium beach front com piscina de borda infinita",
    validacao: "validado",
    comportamentoCompra: "Elite",
    sinaisIntencao: "Busca substituir Booking por sistema próprio",
    redesSociais: "@pdggold",
    site: "www.pdggold.com.br",
    telefone: "8135520037",
    scoreQual: 94,
    scoreValid: 97,
    latitude: -8.5172,
    longitude: -34.9978,
    regiao: "Nordeste",
    status: "convertido",
    createdAt: hoursAgo(81),
    updatedAt: hoursAgo(81),
  },
  {
    id: "seed-conde-tambaba",
    pousada: "Pousada Tambaba Paradise",
    email: "reservas@tambabaparadise.com.br",
    whatsapp: "5583999990038",
    qtdQuartos: 10,
    localPraia: "Praia de Tambaba",
    cidade: "Conde",
    uf: "PB",
    valoresEstimados: "R$ 200 - R$ 380",
    qualificacao: "Naturismo opcional, praia preservada, silêncio",
    validacao: "validado",
    comportamentoCompra: "Tradicional",
    sinaisIntencao: "Sem presença digital significativa",
    redesSociais: "@tambabaparadise",
    telefone: "8333120038",
    scoreQual: 65,
    scoreValid: 58,
    latitude: -7.5172,
    longitude: -34.9672,
    regiao: "Nordeste",
    status: "novo",
    createdAt: hoursAgo(84),
    updatedAt: hoursAgo(84),
  },
  {
    id: "seed-sao-luis-sao",
    pousada: "Pousada São Luis Historic",
    email: "contato@saoluishistoric.com.br",
    whatsapp: "5598999990039",
    qtdQuartos: 12,
    localPraia: "Centro Histórico",
    cidade: "São Luís",
    uf: "MA",
    valoresEstimados: "R$ 220 - R$ 400",
    qualificacao: "Casa colonial no centro histórico, cultura e gastronomia",
    validacao: "pendente",
    comportamentoCompra: "Tradicional",
    sinaisIntencao: "Busca turistas estrangeiros",
    redesSociais: "@saoluishistoric",
    telefone: "9832310039",
    scoreQual: 70,
    scoreValid: 50,
    latitude: -2.5307,
    longitude: -44.3067,
    regiao: "Nordeste",
    status: "novo",
    createdAt: hoursAgo(87),
    updatedAt: hoursAgo(87),
  },
  {
    id: "seed-fernando-de-noronha-fernando",
    pousada: "Pousada Fernando de Noronha Dream",
    email: "reservas@noronhadream.com.br",
    whatsapp: "5581999990040",
    qtdQuartos: 6,
    localPraia: "Praia do Sancho",
    cidade: "Fernando de Noronha",
    uf: "PE",
    valoresEstimados: "R$ 800 - R$ 1.500",
    qualificacao: "Ultra-luxury, experiência exclusiva em ilha paradisíaca",
    validacao: "validado",
    comportamentoCompra: "Elite",
    sinaisIntencao: "100% reservas diretas, quer automação premium",
    redesSociais: "@noronhadream",
    site: "www.noronhadream.com.br",
    telefone: "8136190040",
    scoreQual: 99,
    scoreValid: 100,
    latitude: -3.8547,
    longitude: -32.4231,
    regiao: "Nordeste",
    status: "convertido",
    createdAt: hoursAgo(90),
    updatedAt: hoursAgo(90),
  },
  {
    id: "seed-natal-natal",
    pousada: "Pousada Natal Sun Residence",
    email: "contato@natalsun.com.br",
    whatsapp: "5584999990041",
    qtdQuartos: 17,
    localPraia: "Praia de Ponta Negra",
    cidade: "Natal",
    uf: "RN",
    valoresEstimados: "R$ 280 - R$ 480",
    qualificacao: "Residência com vista para o Morro do Careca",
    validacao: "validado",
    comportamentoCompra: "Moderno",
    sinaisIntencao: "Quer marketing digital para alta temporada",
    redesSociais: "@natalsunresidence",
    site: "www.natalsun.com.br",
    telefone: "8432110041",
    scoreQual: 81,
    scoreValid: 84,
    latitude: -5.8778,
    longitude: -35.1989,
    regiao: "Nordeste",
    status: "contatado",
    createdAt: hoursAgo(93),
    updatedAt: hoursAgo(93),
  },
  {
    id: "seed-manaus-amazonia",
    pousada: "Pousada Amazonia Lodge",
    email: "reservas@amazonialodge.com.br",
    whatsapp: "5592999990050",
    qtdQuartos: 10,
    localPraia: "Rio Negro",
    cidade: "Manaus",
    uf: "AM",
    valoresEstimados: "R$ 350 - R$ 600",
    qualificacao: "Eco-lodge flutuante na selva amazônica",
    validacao: "validado",
    comportamentoCompra: "Moderno",
    sinaisIntencao: "Turismo internacional crescente, precisa de sistema online",
    redesSociais: "@amazonialodge",
    site: "www.amazonialodge.com.br",
    telefone: "9236420050",
    scoreQual: 86,
    scoreValid: 82,
    latitude: -3.119,
    longitude: -60.0217,
    regiao: "Norte",
    status: "contatado",
    createdAt: hoursAgo(96),
    updatedAt: hoursAgo(96),
  },
  {
    id: "seed-belem-belem",
    pousada: "Pousada Belém do Pará",
    email: "contato@belemdopara.com.br",
    whatsapp: "5591999990051",
    qtdQuartos: 9,
    localPraia: "Estação das Docas",
    cidade: "Belém",
    uf: "PA",
    valoresEstimados: "R$ 200 - R$ 380",
    qualificacao: "Pousada cultural, gastronomia paraense, passeios fluviais",
    validacao: "validado",
    comportamentoCompra: "Tradicional",
    sinaisIntencao: "Busca aumentar reservas de turistas nacionais",
    redesSociais: "@belemdopara.pousada",
    site: "www.belemdopara.com.br",
    telefone: "9132290051",
    scoreQual: 75,
    scoreValid: 70,
    latitude: -1.4558,
    longitude: -48.5025,
    regiao: "Norte",
    status: "novo",
    createdAt: hoursAgo(99),
    updatedAt: hoursAgo(99),
  },
  {
    id: "seed-santarem-alter",
    pousada: "Pousada Alter do Chão Riviera",
    email: "reservas@alterdochaoriviera.com.br",
    whatsapp: "5593999990052",
    qtdQuartos: 7,
    localPraia: "Praia do Alter do Chão",
    cidade: "Santarém",
    uf: "PA",
    valoresEstimados: "R$ 280 - R$ 480",
    qualificacao: "Caribe amazônico, praia de água doce cristalina",
    validacao: "validado",
    comportamentoCompra: "Moderno",
    sinaisIntencao: "Alta temporada crescente, precisa de gestão profissional",
    redesSociais: "@alterchaoriviera",
    site: "www.alterdochaoriviera.com.br",
    telefone: "9335220052",
    scoreQual: 82,
    scoreValid: 77,
    latitude: -2.5117,
    longitude: -54.9558,
    regiao: "Norte",
    status: "contatado",
    createdAt: hoursAgo(102),
    updatedAt: hoursAgo(102),
  },
  {
    id: "seed-bonito-bonito",
    pousada: "Pousada Bonito Aquário",
    email: "contato@bonitoaquario.com.br",
    whatsapp: "5567999990060",
    qtdQuartos: 15,
    localPraia: "Rio da Prata",
    cidade: "Bonito",
    uf: "MS",
    valoresEstimados: "R$ 350 - R$ 600",
    qualificacao: "Eco-tourismo premium, flutuação e trilhas",
    validacao: "validado",
    comportamentoCompra: "Moderno",
    sinaisIntencao: "Quero um app para gestão de reservas",
    redesSociais: "@bonitoaquario",
    site: "www.bonitoaquario.com.br",
    telefone: "6732550060",
    scoreQual: 90,
    scoreValid: 88,
    latitude: -21.1264,
    longitude: -56.4944,
    regiao: "Centro-Oeste",
    status: "respondido",
    createdAt: hoursAgo(105),
    updatedAt: hoursAgo(105),
  },
  {
    id: "seed-pocone-pantanal",
    pousada: "Pousada Pantanal Wildlife",
    email: "safary@pantanalwildlife.com.br",
    whatsapp: "5565999990061",
    qtdQuartos: 8,
    localPraia: "Pantanal Norte",
    cidade: "Poconé",
    uf: "MT",
    valoresEstimados: "R$ 500 - R$ 900",
    qualificacao: "Safari lodge, observação de fauna silvestre, experiência única",
    validacao: "validado",
    comportamentoCompra: "Elite",
    sinaisIntencao: "Atende principalmente estrangeiros, quer plataforma internacional",
    redesSociais: "@pantanalwildlife",
    site: "www.pantanalwildlife.com.br",
    telefone: "6533390061",
    scoreQual: 92,
    scoreValid: 90,
    latitude: -17.8419,
    longitude: -56.7139,
    regiao: "Centro-Oeste",
    status: "contatado",
    createdAt: hoursAgo(108),
    updatedAt: hoursAgo(108),
  },
  {
    id: "seed-pirenopolis-pirenopolis",
    pousada: "Pousada Pirenópolis Retreat",
    email: "contato@pirenopolisretreat.com.br",
    whatsapp: "5562999990062",
    qtdQuartos: 12,
    localPraia: "Cachoeiras do Rio do Machado",
    cidade: "Pirenópolis",
    uf: "GO",
    valoresEstimados: "R$ 280 - R$ 480",
    qualificacao: "Cidade histórica com spa, yoga e gastronomia premium",
    validacao: "validado",
    comportamentoCompra: "Moderno",
    sinaisIntencao: "Quer aumentar reservas diretas via marketing digital",
    redesSociais: "@pirenopolisretreat",
    site: "www.pirenopolisretreat.com.br",
    telefone: "6233320062",
    scoreQual: 84,
    scoreValid: 81,
    latitude: -15.8519,
    longitude: -49.0303,
    regiao: "Centro-Oeste",
    status: "contatado",
    createdAt: hoursAgo(111),
    updatedAt: hoursAgo(111),
  },
];

// ============================================================================
// 12 AGENTES — runtime multi-agente com z-ai-web-dev-sdk
// ============================================================================

export const agents: Agent[] = [
  {
    id: "conductor", name: "Conductor", emoji: "🎭",
    role: "Maestro que roteia comandos para o agente certo",
    description: "Roteia mensagens via @menção ou LLM. Status do roster em run() standalone.",
    status: "idle",
    department: "command", tier: "lead",
    defaultModel: "glm-4.7-flash",
    icon: "Command",
    lastRun: hoursAgo(0.5),
    tasksToday: 0, tasksTotal: 0, successRate: 0,
  },
  {
    id: "comms-agent", name: "Comms Agent", emoji: "💬",
    role: "Comunicação unificada: WhatsApp, Instagram, email",
    description: "Resume e prioriza mensagens dos canais de comunicação.",
    status: "idle",
    department: "comms", tier: "specialist",
    defaultModel: "glm-4.7-flash",
    icon: "MessageSquare",
    lastRun: hoursAgo(2),
    tasksToday: 0, tasksTotal: 0, successRate: 0,
  },
  {
    id: "finance-agent", name: "Finance Agent", emoji: "💰",
    role: "DRE, fluxo de caixa, despesas. Análise financeira com LLM",
    description: "Análise financeira com recomendações. Consulta Prisma para métricas.",
    status: "idle",
    department: "finance", tier: "specialist",
    defaultModel: "glm-4.7",
    icon: "DollarSign",
    lastRun: hoursAgo(8),
    tasksToday: 0, tasksTotal: 0, successRate: 0,
  },
  {
    id: "operations-agent", name: "Operations Agent", emoji: "⚙️",
    role: "Limpeza, manutenção, checklists automáticos",
    description: "Prioriza tarefas do dia. Tarefas operacionais automatizadas.",
    status: "idle",
    department: "operations", tier: "specialist",
    defaultModel: "glm-4.7-flash",
    icon: "ListChecks",
    lastRun: hoursAgo(1.5),
    tasksToday: 0, tasksTotal: 0, successRate: 0,
  },
  {
    id: "goals-agent", name: "Goals Agent", emoji: "🎯",
    role: "KPIs e metas com projeção linear",
    description: "Identifica risco de não bater meta. Projeção baseada em dados reais.",
    status: "idle",
    department: "finance", tier: "worker",
    defaultModel: "glm-4.7",
    icon: "Target",
    lastRun: hoursAgo(6),
    tasksToday: 0, tasksTotal: 0, successRate: 0,
  },
  {
    id: "leads-agent", name: "Leads Agent", emoji: "📍",
    role: "Funil comercial e mapa nacional de leads",
    description: "Prioriza regiões por fit. Qualifica leads da landing page.",
    status: "idle",
    department: "sales", tier: "specialist",
    defaultModel: "glm-4.7-flash",
    icon: "MapPin",
    lastRun: hoursAgo(0.8),
    tasksToday: 0, tasksTotal: 0, successRate: 0,
  },
  {
    id: "data-agent", name: "Data Agent", emoji: "🗄️",
    role: "Busca na base de conhecimento (G-Brain)",
    description: "Responde perguntas sobre políticas, manuais. Retrieval com LLM.",
    status: "idle",
    department: "tech", tier: "worker",
    defaultModel: "glm-4.7-flash",
    icon: "Database",
    lastRun: hoursAgo(4),
    tasksToday: 0, tasksTotal: 0, successRate: 0,
  },
  {
    id: "cerebro-agent", name: "Cérebro Agent", emoji: "🧠",
    role: "Detecção de anomalias, análise preditiva, risco de churn",
    description: "IA central com raciocínio profundo. Detecta padrões anômalos.",
    status: "idle",
    department: "tech", tier: "specialist",
    defaultModel: "glm-4.7",
    icon: "Brain",
    lastRun: hoursAgo(1),
    tasksToday: 0, tasksTotal: 0, successRate: 0,
  },
  {
    id: "refactor-agent", name: "Refactor Agent", emoji: "🔧",
    role: "Auto-aprendizado. Sugere melhorias no próprio sistema",
    description: "Analisa padrões de erro e sugere refatorações de código.",
    status: "idle",
    department: "tech", tier: "worker",
    defaultModel: "glm-4.7",
    icon: "Code",
    lastRun: hoursAgo(12),
    tasksToday: 0, tasksTotal: 0, successRate: 0,
  },
  {
    id: "whatsapp-worker", name: "WhatsApp Worker", emoji: "📱",
    role: "Status do WhatsApp conectado e mensagens processadas",
    description: "Monitora conexão WhatsApp Cloud API e mensagens processadas.",
    status: "idle",
    department: "comms", tier: "worker",
    defaultModel: "glm-4.7-flash",
    icon: "Smartphone",
    lastRun: hoursAgo(0.2),
    tasksToday: 0, tasksTotal: 0, successRate: 0,
  },
  {
    id: "airbnb-worker", name: "Airbnb/iCal Worker", emoji: "🏠",
    role: "Sincronização iCal, reservas e ocupação",
    description: "Sincroniza calendários Airbnb/Booking via iCal. Monitora ocupação.",
    status: "idle",
    department: "operations", tier: "worker",
    defaultModel: "glm-4.7-flash",
    icon: "Home",
    lastRun: hoursAgo(3),
    tasksToday: 0, tasksTotal: 0, successRate: 0,
  },
  {
    id: "onboarding-agent", name: "Onboarding Agent", emoji: "👋",
    role: "Orienta novos tenants no setup inicial do Zélla",
    description: "Guia novos clientes pelo processo de onboarding.",
    status: "idle",
    department: "sales", tier: "worker",
    defaultModel: "glm-4.7-flash",
    icon: "UserPlus",
    lastRun: hoursAgo(5),
    tasksToday: 0, tasksTotal: 0, successRate: 0,
  },
];

// ============================================================================
// 6 INTEGRAÇÕES — live connections
// ============================================================================

export const integrations: Integration[] = [
  {
    id: "whatsapp-cloud-api", name: "WhatsApp Cloud API", category: "messaging",
    status: "online", latencyMs: 245,
    lastCheck: hoursAgo(0.05),
    endpoint: "graph.facebook.com/v18.0/{phone_id}/messages",
    purpose: "Envio e recebimento de mensagens WhatsApp 24/7",
  },
  {
    id: "airbnb-oauth", name: "Airbnb OAuth", category: "booking",
    status: "online", latencyMs: 892,
    lastCheck: hoursAgo(0.05),
    endpoint: "api.airbnb.com/v2/*",
    purpose: "Sincroniza calendário e reservas Airbnb",
  },
  {
    id: "mercado-pago", name: "Mercado Pago", category: "payment",
    status: "online", latencyMs: 412,
    lastCheck: hoursAgo(0.05),
    endpoint: "api.mercadopago.com/v1/*",
    purpose: "Geração de PIX e processamento de pagamentos",
  },
  {
    id: "openai", name: "Z-AI SDK (GLM)", category: "llm",
    status: "online", latencyMs: 320,
    lastCheck: hoursAgo(0.05),
    endpoint: "z-ai-web-dev-sdk · chat.completions",
    purpose: "LLM principal — glm-4.7 para agentes de análise",
    isLLM: true,
  },
  {
    id: "groq", name: "Z-AI SDK (GLM Flash)", category: "llm",
    status: "online", latencyMs: 120,
    lastCheck: hoursAgo(0.05),
    endpoint: "z-ai-web-dev-sdk · chat.completions",
    purpose: "LLM rápido — glm-4.7-flash para routing/comms",
    isLLM: true,
  },
  {
    id: "vercel-postgres", name: "Vercel Postgres", category: "database",
    status: "online", latencyMs: 18,
    lastCheck: hoursAgo(0.05),
    endpoint: "postgres://default@*.*-pooler.region.aws.vercel-storage.com",
    purpose: "Banco de dados principal — leads, agentes, eventos",
  },
];

// ============================================================================
// EVENTOS DO CÉREBRO — feed ao vivo
// ============================================================================

export const brainEvents: BrainEvent[] = [
  { id: "ev-01", type: "info", agent: "conductor", message: "Aguardando primeira execução INIT", at: hoursAgo(2) },
  { id: "ev-02", type: "ok", agent: "cerebro", message: "Cérebro analisou padrões de ocupação — sem anomalias nas últimas 24h.", detail: "Ocupação média: 0% (modo mock). Threshold: 3σ.", at: hoursAgo(1.5), confidence: 0.95 },
  { id: "ev-03", type: "warn", agent: "conductor", message: "Conductor routeou 0 mensagens — sistema em modo mock.", at: hoursAgo(1) },
  { id: "ev-04", type: "info", agent: "tech", message: "Aguardando primeira execução real para alimentar RefactorSuggester.", at: hoursAgo(0.5) },
  { id: "ev-05", type: "info", agent: "cerebro", message: "12 agentes prontos para execução. Use a aba Agentes Vivos.", at: hoursAgo(0.2) },
];

// ============================================================================
// KPIs do Operador
// ============================================================================

export const operatorKPIs: OperatorKPI[] = [
  { label: "MRR", value: "R$ 0", hint: "0% vs mês anterior", trend: "stable" },
  { label: "Clientes", value: 0, hint: "ativos" },
  { label: "Mensagens 24h", value: 0, hint: "via WhatsApp" },
  { label: "Reservas 7d", value: 0, hint: "confirmadas" },
  { label: "Agentes ativos", value: "0/12", hint: "prontos p/ execução" },
  { label: "Cérebro accuracy", value: "—", hint: "sem dados ainda" },
];

// ============================================================================
// HELPERS
// ============================================================================

export const formatBRL = (v: number) =>
  v.toLocaleString("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });

export const formatPct = (v: number) => `${(v * 100).toFixed(1).replace(".", ",")}%`;

export const relativeTime = (isoDate: string): string => {
  const diff = Date.now() - new Date(isoDate).getTime();
  const min = Math.floor(diff / 60000);
  if (min < 1) return "agora";
  if (min < 60) return `há ${min} min`;
  const h = Math.floor(min / 60);
  if (h < 24) return `há ${h}h`;
  const d = Math.floor(h / 24);
  return `há ${d}d`;
};

export const formatLatency = (ms: number): string => {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(2)}s`;
};

// ============================================================================
// STATS — derivado dos leads (espelha API /api/leads/analytics)
// ============================================================================

export function computeStats(leadList: Lead[]): LeadsStats {
  const total = leadList.length;
  const porUf = new Map<string, number>();
  const porStatus = new Map<string, number>();
  const porRegiao = new Map<string, number>();
  let sumQual = 0, sumValid = 0;
  for (const l of leadList) {
    porUf.set(l.uf ?? "", (porUf.get(l.uf ?? "") ?? 0) + 1);
    porStatus.set(l.status, (porStatus.get(l.status) ?? 0) + 1);
    if (l.region) porRegiao.set(l.region, (porRegiao.get(l.region) ?? 0) + 1);
    sumQual += l.avgScore ?? 0;
    sumValid += l.scoreValid;
  }
  return {
    total,
    porUf: [...porUf.entries()].map(([uf, count]) => ({ uf, count })),
    porStatus: [...porStatus.entries()].map(([status, count]) => ({ status: status as any, count })),
    porRegiao: [...porRegiao.entries()].map(([regiao, count]) => ({ regiao: regiao as any, count })),
    avgScore: total ? Math.round(sumQual / total) : 0,
    avgScoreValid: total ? Math.round(sumValid / total) : 0,
  };
}

// ===== MOCK DATA ADICIONAL PARA ZCC v5 =====

export const activity: ActivityEntry[] = [
  { type: "lead", message: "Nova pousada cadastrada em Paraty-RJ", timestamp: hoursAgo(1), user: "sistema", priority: "medium" },
  { type: "reservation", message: "Reserva confirmada — Pousada Serenity", timestamp: hoursAgo(2), user: "IA Zélla", priority: "low" },
  { type: "payment", message: "PIX recebido R$ 397,00 — Plano PRO", timestamp: hoursAgo(3), user: "Mercado Pago", priority: "medium" },
  { type: "alert", message: "IA offline detectada — Pousada Recanto", timestamp: hoursAgo(5), user: "Cérebro", priority: "urgent" },
  { type: "message", message: "Hóspede pediu atendente humano", timestamp: hoursAgo(6), user: "WhatsApp", priority: "high" },
  { type: "system", message: "Cron learning-cycle executado com sucesso", timestamp: hoursAgo(8), user: "sistema", priority: "low" },
];

export const ddcPanels = [
  { id: "pousada-1", name: "Pousada Serenity Paraty", label: "Pousada Serenity Paraty", niche: "pousada", plan: "PRO", status: "active", revenue: 397 },
  { id: "pousada-2", name: "Recanto dos Pássaros", label: "Recanto dos Pássaros", niche: "pousada", plan: "LITE", status: "active", revenue: 197 },
  { id: "airbnb-1", name: "Flat Centro RJ", label: "Flat Centro RJ", niche: "airbnb", plan: "MAX", status: "active", revenue: 797 },
  { id: "airbnb-2", name: "Loft Paulista SP", label: "Loft Paulista SP", niche: "airbnb", plan: "PRO", status: "active", revenue: 397 },
];
