/**
 * Zélla — Notification Seed (MOCK MODE)
 *
 * Seeds the in-memory store with realistic notifications covering all 9
 * categories. Run on app boot (or on demand via /api/ddc/notifications/seed).
 *
 * Each notification is timestamped relative to NOW to look realistic.
 */

import { memoryStore } from './store';
import type { DDCNotification, NotificationNiche } from './types';

function minutesAgo(min: number): string {
  return new Date(Date.now() - min * 60 * 1000).toISOString();
}

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 60 * 60 * 1000).toISOString();
}

function daysAgo(d: number): string {
  return new Date(Date.now() - d * 24 * 60 * 60 * 1000).toISOString();
}

// Counter for unique IDs
let seedSeq = 0;
function nid(): string {
  seedSeq++;
  return `seed-n-${seedSeq}`;
}

// ─── Seed notifications for a niche ────────────────────────────────────────
function buildSeed(niche: NotificationNiche): DDCNotification[] {
  const common = {
    status: 'unread' as const,
    readAt: null,
    tenantId: 'mock-tenant-001',
    userId: 'mock-user-001',
    propertyId: niche === 'pousada' ? 'mock-pousada-001' : 'mock-airbnb-001',
  };

  return [
    // ═══ RESERVATIONS ═══
    {
      id: nid(),
      niche,
      category: 'reservations',
      type: 'booking.created',
      priority: 'high',
      title: 'Nova reserva solicitada',
      message: 'Carlos Mendes quer reservar Suíte Vista Mar (15/08 → 18/08)',
      source: 'reservation_flow',
      entityId: 'BK-7821',
      metadata: { guestName: 'Carlos Mendes', roomName: 'Suíte Vista Mar', checkIn: '15/08', checkOut: '18/08' },
      actionUrl: `/ddc/${ niche}`,
      actionLabel: 'Ver reserva',
      planAvailability: 'ALL',
      createdAt: minutesAgo(2),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'reservations',
      type: 'booking.confirmed',
      priority: 'high',
      title: 'Reserva confirmada',
      message: 'Reserva #BK-7819 confirmada para Mariana Silva',
      source: 'reservation_flow',
      entityId: 'BK-7819',
      metadata: { guestName: 'Mariana Silva', bookingId: 'BK-7819' },
      actionUrl: `/ddc/${ niche}`,
      actionLabel: 'Ver reserva',
      planAvailability: 'ALL',
      createdAt: minutesAgo(28),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'reservations',
      type: 'booking.checkin_today',
      priority: 'high',
      title: 'Check-in hoje',
      message: `João Pereira chega hoje no ${ niche === 'pousada' ? 'Chalé Vista Lago' : 'Loft Centro'}`,
      source: 'reservation_flow',
      metadata: { guestName: 'João Pereira', roomName: niche === 'pousada' ? 'Chalé Vista Lago' : 'Loft Centro' },
      actionUrl: `/ddc/${ niche}`,
      actionLabel: 'Ver detalhes',
      planAvailability: 'ALL',
      createdAt: hoursAgo(1),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'reservations',
      type: 'booking.checkout_today',
      priority: 'high',
      title: 'Check-out hoje',
      message: 'Ana Beatriz sai hoje até as 11h',
      source: 'reservation_flow',
      metadata: { guestName: 'Ana Beatriz', roomName: 'Suíte Premium' },
      planAvailability: 'ALL',
      createdAt: hoursAgo(2),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'reservations',
      type: 'booking.cancelled',
      priority: 'medium',
      title: 'Reserva cancelada',
      message: 'Roberto Almeida cancelou a reserva #BK-7801',
      source: 'reservation_flow',
      entityId: 'BK-7801',
      metadata: { guestName: 'Roberto Almeida', bookingId: 'BK-7801' },
      planAvailability: 'ALL',
      createdAt: hoursAgo(5),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'reservations',
      type: 'booking.escalated',
      priority: 'urgent',
      title: 'Reserva escalonada para humano',
      message: 'Fernanda Costa solicitou atendimento humano — conversa escalonada',
      source: 'whatsapp',
      entityId: 'CV-9012',
      metadata: { guestName: 'Fernanda Costa', conversationId: 'CV-9012' },
      actionUrl: `/ddc/${ niche}`,
      actionLabel: 'Responder',
      planAvailability: 'ALL',
      createdAt: minutesAgo(8),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'reservations',
      type: 'booking.double_booking',
      priority: 'urgent',
      title: 'Conflito de reservas',
      message: 'Dupla reserva detectada no Suíte Master em 22/08',
      source: 'reservation_flow',
      metadata: { roomName: 'Suíte Master', date: '22/08' },
      planAvailability: 'ALL',
      createdAt: minutesAgo(15),
      ...common,
    },

    // ═══ FINANCIAL ═══
    {
      id: nid(),
      niche,
      category: 'financial',
      type: 'payment.pix_received',
      priority: 'high',
      title: 'PIX recebido',
      message: 'R$ 1.500,00 confirmado de Carlos Mendes',
      source: 'webhook_payment',
      entityId: 'PAY-5521',
      metadata: { amount: '1500.00', guestName: 'Carlos Mendes' },
      planAvailability: 'ALL',
      createdAt: minutesAgo(3),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'financial',
      type: 'payment.pix_received',
      priority: 'high',
      title: 'PIX recebido',
      message: 'R$ 890,00 confirmado de Mariana Silva',
      source: 'webhook_payment',
      entityId: 'PAY-5519',
      metadata: { amount: '890.00', guestName: 'Mariana Silva' },
      planAvailability: 'ALL',
      createdAt: minutesAgo(28),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'financial',
      type: 'payment.overdue',
      priority: 'urgent',
      title: 'Pagamento em atraso',
      message: 'R$ 2.200,00 de Bruno Carvalho venceu há 3 dias',
      source: 'webhook_payment',
      metadata: { amount: '2200.00', guestName: 'Bruno Carvalho', days: 3 },
      actionUrl: `/ddc/${ niche}`,
      actionLabel: 'Cobrar agora',
      planAvailability: 'ALL',
      createdAt: hoursAgo(6),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'financial',
      type: 'payment.failed',
      priority: 'urgent',
      title: 'Falha no pagamento',
      message: 'Pagamento de R$ 1.200,00 falhou para Patricia Lima',
      source: 'webhook_payment',
      metadata: { amount: '1200.00', guestName: 'Patricia Lima' },
      planAvailability: 'ALL',
      createdAt: hoursAgo(7),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'financial',
      type: 'financial.daily_summary',
      priority: 'low',
      title: 'Resumo financeiro do dia',
      message: 'R$ 4.890,00 recebidos em 6 transações',
      source: 'manual',
      metadata: { total: '4890.00', count: 6 },
      planAvailability: 'PRO',
      createdAt: hoursAgo(20),
      ...common,
    },

    // ═══ GUESTS ═══
    {
      id: nid(),
      niche,
      category: 'guests',
      type: 'guest.new_lead',
      priority: 'medium',
      title: 'Novo lead recebido',
      message: 'Ricardo Nunes iniciou conversa via WhatsApp',
      source: 'whatsapp',
      metadata: { guestName: 'Ricardo Nunes', channel: 'WhatsApp' },
      planAvailability: 'ALL',
      createdAt: minutesAgo(5),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'guests',
      type: 'guest.hot_lead',
      priority: 'high',
      title: 'Lead quente detectado',
      message: 'Camila Rocha tem alta intenção de reserva (score 87)',
      source: 'whatsapp',
      metadata: { guestName: 'Camila Rocha', score: 87 },
      planAvailability: 'ALL',
      createdAt: minutesAgo(12),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'guests',
      type: 'guest.complaint',
      priority: 'urgent',
      title: 'Reclamação registrada',
      message: 'Hóspede do quarto 12 reclamou sobre ar-condicionado',
      source: 'whatsapp',
      metadata: { guestName: 'Hóspede 12', topic: 'ar-condicionado' },
      planAvailability: 'ALL',
      createdAt: hoursAgo(3),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'guests',
      type: 'guest.returning',
      priority: 'medium',
      title: 'Hóspede retornando',
      message: 'Sandra Meyer já se hospedou 4× conosco',
      source: 'whatsapp',
      metadata: { guestName: 'Sandra Meyer', count: 4 },
      planAvailability: 'PRO',
      createdAt: hoursAgo(10),
      ...common,
    },

    // ═══ AI / Cérebro ═══
    {
      id: nid(),
      niche,
      category: 'ai',
      type: 'ai.pattern_learned',
      priority: 'low',
      title: 'Novo padrão aprendido',
      message: 'Cérebro aprendeu: "Hóspedes perguntando sobre Wi-Fi no check-in"',
      source: 'cerebro',
      metadata: { pattern: 'Hóspedes perguntando sobre Wi-Fi no check-in' },
      planAvailability: 'ALL',
      createdAt: minutesAgo(45),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'ai',
      type: 'ai.confidence_drop',
      priority: 'high',
      title: 'Queda de confiança da IA',
      message: 'Confiança caiu para 68% em 12 conversas (meta: 85%)',
      source: 'cerebro',
      metadata: { percent: 68, count: 12 },
      planAvailability: 'PRO',
      createdAt: hoursAgo(2),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'ai',
      type: 'ai.anomaly_response_time',
      priority: 'high',
      title: 'Tempo de resposta anômalo',
      message: 'Tempo médio subiu para 22s (normal: 8s)',
      source: 'cerebro',
      metadata: { seconds: 22 },
      planAvailability: 'PRO',
      createdAt: hoursAgo(4),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'ai',
      type: 'ai.cost_alert',
      priority: 'high',
      title: 'Alerta de custo de IA',
      message: 'Custo de tokens R$ 342 este mês (limite: R$ 400)',
      source: 'cerebro',
      metadata: { amount: '342', limit: '400' },
      planAvailability: 'MAX',
      createdAt: hoursAgo(8),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'ai',
      type: 'ai.offline',
      priority: 'urgent',
      title: 'IA Cérebro offline',
      message: 'Cérebro parou de responder há 12 minutos — intervenção necessária',
      source: 'cerebro',
      metadata: { downtime: '12 min' },
      planAvailability: 'ALL',
      createdAt: minutesAgo(13),
      ...common,
    },

    // ═══ OPERATIONS ═══
    {
      id: nid(),
      niche,
      category: 'operations',
      type: 'ical.sync_success',
      priority: 'low',
      title: 'iCal sincronizado',
      message: '8 atualizações de calendário importadas com sucesso',
      source: 'ical',
      metadata: { count: 8 },
      planAvailability: 'ALL',
      createdAt: hoursAgo(1),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'operations',
      type: 'ical.sync_failed',
      priority: 'high',
      title: 'Falha na sincronização iCal',
      message: 'Não foi possível sincronizar o calendário Airbnb iCal',
      source: 'ical',
      metadata: { calendarName: 'Airbnb iCal' },
      planAvailability: 'ALL',
      createdAt: hoursAgo(3),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'operations',
      type: 'ota.token_expired',
      priority: 'high',
      title: 'Token OTA expirado',
      message: 'Reconectar Booking.com para continuar sincronização',
      source: 'ota_booking',
      metadata: { provider: 'Booking.com' },
      actionUrl: `/ddc/${ niche}`,
      actionLabel: 'Reconectar',
      planAvailability: 'PRO',
      createdAt: hoursAgo(5),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'operations',
      type: 'ops.cleaning_reminder',
      priority: 'medium',
      title: 'Limpeza programada',
      message: 'Suíte 04 precisa de limpeza antes das 14h',
      source: 'reservation_flow',
      metadata: { roomName: 'Suíte 04' },
      planAvailability: 'PRO',
      createdAt: hoursAgo(2),
      ...common,
    },

    // ═══ MARKETING ═══
    {
      id: nid(),
      niche,
      category: 'marketing',
      type: 'ads.google.budget_low',
      priority: 'medium',
      title: 'Orçamento Google Ads baixo',
      message: 'Campanha "Pousada Verão" tem R$ 45,00 restante',
      source: 'google_ads',
      metadata: { campaign: 'Pousada Verão', amount: '45.00' },
      actionUrl: `/ddc/${ niche}`,
      actionLabel: 'Ver campanha',
      planAvailability: 'PRO',
      createdAt: hoursAgo(6),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'marketing',
      type: 'ads.meta.budget_low',
      priority: 'medium',
      title: 'Orçamento Meta Ads baixo',
      message: 'Campanha "Airbnb SP" tem R$ 80,00 restante',
      source: 'meta_ads',
      metadata: { campaign: 'Airbnb SP', amount: '80.00' },
      planAvailability: 'PRO',
      createdAt: hoursAgo(9),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'marketing',
      type: 'ads.meta.performance',
      priority: 'low',
      title: 'Relatório Meta Ads',
      message: 'Alcance 12.480 • 87 leads • CPL R$ 4,32',
      source: 'meta_ads',
      metadata: { reach: 12480, leads: 87, cpl: '4.32' },
      planAvailability: 'PRO',
      createdAt: hoursAgo(15),
      ...common,
    },

    // ═══ SYSTEM ═══
    {
      id: nid(),
      niche,
      category: 'system',
      type: 'system.plan_expiring',
      priority: 'high',
      title: 'Plano expira em 5 dias',
      message: 'Renove PRO para manter todos os recursos',
      source: 'plan_system',
      metadata: { days: 5, plan: 'PRO' },
      actionUrl: '/dashboard/settings/billing',
      actionLabel: 'Renovar agora',
      planAvailability: 'ALL',
      createdAt: hoursAgo(12),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'system',
      type: 'system.invoice_ready',
      priority: 'medium',
      title: 'Fatura disponível',
      message: 'Fatura de R$ 197,00 referente a Agosto/2025',
      source: 'plan_system',
      metadata: { amount: '197.00', period: 'Agosto/2025' },
      actionUrl: '/dashboard/settings/billing',
      actionLabel: 'Ver fatura',
      planAvailability: 'ALL',
      createdAt: daysAgo(1),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'system',
      type: 'system.security_alert',
      priority: 'urgent',
      title: 'Alerta de segurança',
      message: 'Login suspeito bloqueado de 187.45.12.8 (São Paulo)',
      source: 'plan_system',
      metadata: { ip: '187.45.12.8' },
      planAvailability: 'ALL',
      createdAt: daysAgo(2),
      ...common,
    },

    // ═══ ACHIEVEMENTS ═══
    {
      id: nid(),
      niche,
      category: 'achievements',
      type: 'achievement.milestone_10',
      priority: 'medium',
      title: 'Marco: 10 reservas',
      message: 'Você atingiu 10 reservas via Zélla este mês!',
      source: 'achievement_engine',
      metadata: {},
      planAvailability: 'PARCEIRO_ZELLA',
      createdAt: hoursAgo(18),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'achievements',
      type: 'achievement.revenue_record',
      priority: 'high',
      title: 'Recorde de receita mensal',
      message: 'R$ 28.450 — maior receita mensal da história!',
      source: 'achievement_engine',
      metadata: { amount: '28450' },
      planAvailability: 'PARCEIRO_ZELLA',
      createdAt: daysAgo(1),
      ...common,
    },

    // ═══ EXTERNAL ═══
    {
      id: nid(),
      niche,
      category: 'external',
      type: 'external.review_positive',
      priority: 'medium',
      title: 'Nova avaliação 5 estrelas',
      message: 'Marina Souza deixou 5 estrelas no Booking.com',
      source: 'ota_booking',
      metadata: { guestName: 'Marina Souza', stars: 5 },
      planAvailability: 'ALL',
      createdAt: hoursAgo(4),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'external',
      type: 'external.review_negative',
      priority: 'high',
      title: 'Nova avaliação negativa',
      message: 'Hóspede deixou 2 estrelas — resposta necessária',
      source: 'ota_booking',
      metadata: { guestName: 'Hóspede anônimo', stars: 2 },
      actionUrl: `/ddc/${ niche}`,
      actionLabel: 'Responder',
      planAvailability: 'ALL',
      createdAt: hoursAgo(7),
      ...common,
    },
    {
      id: nid(),
      niche,
      category: 'external',
      type: 'external.weather_alert',
      priority: 'medium',
      title: 'Alerta climático',
      message: 'Previsão de chuva forte em 16/08 — avise os hóspedes',
      source: 'manual',
      metadata: { condition: 'chuva forte', date: '16/08' },
      planAvailability: 'ALL',
      createdAt: hoursAgo(11),
      ...common,
    },

    // Some "read" old notifications for realism
    {
      id: nid(),
      niche,
      category: 'reservations',
      type: 'booking.confirmed',
      priority: 'high',
      title: 'Reserva confirmada',
      message: 'Reserva #BK-7790 confirmada para Eduardo Lima',
      source: 'reservation_flow',
      entityId: 'BK-7790',
      metadata: { guestName: 'Eduardo Lima', bookingId: 'BK-7790' },
      planAvailability: 'ALL',
      createdAt: daysAgo(2),
      // Override `common` to mark as read
      ...common,
      status: 'read',
      readAt: hoursAgo(30),
    },
    {
      id: nid(),
      niche,
      category: 'financial',
      type: 'payment.pix_received',
      priority: 'high',
      title: 'PIX recebido',
      message: 'R$ 1.100,00 confirmado de Eduardo Lima',
      source: 'webhook_payment',
      metadata: { amount: '1100.00', guestName: 'Eduardo Lima' },
      planAvailability: 'ALL',
      createdAt: daysAgo(2),
      ...common,
      status: 'read',
      readAt: daysAgo(2),
    },
  ];
}

// ─── Seed function ─────────────────────────────────────────────────────────
let seeded = false;

export function seedNotifications(opts: { force?: boolean } = {}): {
  inserted: number;
  total: number;
  alreadySeeded: boolean;
} {
  if (seeded && !opts.force) {
    return { inserted: 0, total: memoryStore.size(), alreadySeeded: true };
  }

  const all: DDCNotification[] = [
    ...buildSeed('pousada'),
    ...buildSeed('airbnb'),
    // System-wide notifications for "all" niches
    {
      id: nid(),
      niche: 'all',
      category: 'system',
      type: 'system.feature_released',
      priority: 'low',
      title: 'Novo recurso disponível',
      message: 'Centro de Notificações Mobile agora está disponível no seu plano',
      source: 'plan_system',
      status: 'unread',
      readAt: null,
      tenantId: 'mock-tenant-001',
      metadata: { feature: 'Centro de Notificações Mobile' },
      planAvailability: 'ALL',
      createdAt: hoursAgo(1),
    },
  ];

  memoryStore.bulkInsert(all);
  seeded = true;

  return { inserted: all.length, total: memoryStore.size(), alreadySeeded: false };
}

export function isSeeded(): boolean {
  return seeded;
}

export function resetSeed(): void {
  seeded = false;
  memoryStore.clear();
}
