import { NextRequest, NextResponse } from 'next/server';
import { withSecurity } from '@/lib/security/api-shield';
import { db } from '@/lib/db';
import { generateSlug } from '@/lib/slug-utils';
import { resolveTenantId } from '@/lib/ddc/auth-utils';

// GET /api/ddc/guest-guide — List guest guides for tenant
async function getHandler(request: NextRequest) {
  try {
    const authenticatedTenantId = await resolveTenantId();
    if (!authenticatedTenantId) {
      return NextResponse.json({ success: false, error: 'Não autorizado' }, { status: 401 });
    }
    const tenantId = authenticatedTenantId;

    const guides = await db.guestGuide.findMany({
      where: { tenantId },
      orderBy: { updatedAt: 'desc' },
    });

    const stats = {
      totalGuides: guides.length,
      activeGuides: guides.filter((g: any) => g.status === 'active').length,
      totalViews: guides.reduce((sum: number, g: any) => sum + g.viewCount, 0),
      autoGenerated: guides.filter((g: any) => g.autoGenerated).length,
    };

    return NextResponse.json({ success: true, guides, stats });
  } catch (error) {
    console.error('[GuestGuide] GET error:', error);
    return NextResponse.json({ success: false, error: 'Internal server error' }, { status: 500 });
  }
}

// POST /api/ddc/guest-guide — Create or auto-generate a guest guide
async function postHandler(request: NextRequest) {
  try {
    const authenticatedTenantId = await resolveTenantId();
    if (!authenticatedTenantId) {
      return NextResponse.json({ success: false, error: 'Não autorizado' }, { status: 401 });
    }
    const tenantId = authenticatedTenantId;

    const body = await request.json();
    const { airbPropertyId, propertyId, autoGenerate, welcomeMessage, sections, title } = body;

    if (autoGenerate) {
      // Auto-generate guide from property data
      let guideTitle = title || 'Guia do Hóspede';
      const guideSections: any[] = [];
      let slugBase = 'guia';

      if (airbPropertyId) {
        const airbProp = await db.airBProperty.findFirst({
          where: { id: airbPropertyId, tenantId },
          include: { regionalKnowledge: { orderBy: { rating: 'desc' } } },
        });

        if (!airbProp) {
          return NextResponse.json({ success: false, error: 'Airbnb property not found' }, { status: 404 });
        }

        slugBase = airbProp.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40);
        guideTitle = `Guia do Hóspede — ${airbProp.name}`;

        // Build sections from AirBProperty data
        const essentialsItems: any[] = [];
        if (airbProp.wifiName) {
          essentialsItems.push({ label: 'Wi-Fi', network: airbProp.wifiName, password: airbProp.wifiPassword || 'Pergunte ao anfitrião', type: 'wifi' });
        }
        essentialsItems.push({ label: 'Check-in', value: airbProp.checkinTime || '15:00', type: 'checkin' });
        essentialsItems.push({ label: 'Check-out', value: airbProp.checkoutTime || '11:00', type: 'checkout' });

        guideSections.push({ type: 'essentials', title: 'Essenciais', items: essentialsItems });

        // House Rules
        if (airbProp.houseRules && airbProp.houseRules !== '[]') {
          try {
            const rules = JSON.parse(airbProp.houseRules);
            if (rules.length > 0) {
              guideSections.push({ type: 'rules', title: 'Regras da Casa', items: rules.map((r: any) => ({ label: r })) });
            }
          } catch {}
        }

        // Host Knowledge
        if (airbProp.hostKnowledge && airbProp.hostKnowledge !== '[]') {
          try {
            const tips = JSON.parse(airbProp.hostKnowledge);
            if (tips.length > 0) {
              guideSections.push({ type: 'tips', title: 'Dicas do Anfitrião', items: tips.map((t: any) => ({ label: typeof t === 'string' ? t : t.text || t.tip || String(t) })) });
            }
          } catch {}
        }

        // Neighborhood Tips
        if (airbProp.neighborhoodTips && airbProp.neighborhoodTips !== '[]') {
          try {
            const nTips = JSON.parse(airbProp.neighborhoodTips);
            if (nTips.length > 0) {
              guideSections.push({ type: 'neighborhood', title: 'Arredores', items: nTips.map((t: any) => ({ label: typeof t === 'string' ? t : t.text || t.tip || String(t) })) });
            }
          } catch {}
        }

        // Emergency Contacts
        if (airbProp.emergencyContacts && airbProp.emergencyContacts !== '[]') {
          try {
            const contacts = JSON.parse(airbProp.emergencyContacts);
            if (contacts.length > 0) {
              guideSections.push({ type: 'emergency', title: 'Contatos de Emergência', items: contacts.map((c: any) => ({ label: typeof c === 'string' ? c : c.name || String(c), phone: typeof c === 'object' ? c.phone : undefined })) });
            }
          } catch {}
        }

        // Regional Knowledge (restaurants, supermarkets, attractions)
        const regionalCategories: Record<string, string> = { restaurant: 'Restaurantes', supermarket: 'Supermercados', attraction: 'Passeios', pharmacy: 'Farmácias', transport: 'Transporte' };
        for (const [catKey, catName] of Object.entries(regionalCategories)) {
          const items = airbProp.regionalKnowledge.filter(k => k.category === catKey);
          if (items.length > 0) {
            guideSections.push({ type: catKey, title: catName, items: items.map(i => ({
              label: i.name, distance: i.distance || '', walkingTime: i.walkingTimeMin ? `${i.walkingTimeMin} min` : '', rating: i.rating || 0,
            })) });
          }
        }

        // FAQ
        guideSections.push({ type: 'faq', title: 'Perguntas Frequentes', items: [
          { label: 'Qual a senha do Wi-Fi?', answer: airbProp.wifiPassword || 'Pergunte ao anfitrião' },
          { label: 'Horário de check-in?', answer: airbProp.checkinTime || '15:00' },
          { label: 'Horário de check-out?', answer: airbProp.checkoutTime || '11:00' },
          { label: 'O que fazer se tiver problema?', answer: 'Entre em contato pelo WhatsApp do anfitrião' },
        ] });
      } else if (propertyId) {
        // Pousada/Property guide
        const property = await db.property.findFirst({
          where: { id: propertyId, tenantId },
          include: { rooms: true },
        });

        if (!property) {
          return NextResponse.json({ success: false, error: 'Property not found' }, { status: 404 });
        }

        slugBase = property.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40);
        guideTitle = `Guia do Hóspede — ${property.name}`;

        // Build from Property + KnowledgeEntry
        const policies = await db.knowledgeEntry.findMany({
          where: { tenantId, category: 'policies' },
          select: { question: true, answer: true },
          take: 20,
        });

        const amenities = await db.knowledgeEntry.findMany({
          where: { tenantId, category: 'amenities' },
          select: { question: true, answer: true },
          take: 20,
        });

        // Essentials
        const essentialsItems: any[] = [];
        essentialsItems.push({ label: 'Check-in', value: '14:00', type: 'checkin' });
        essentialsItems.push({ label: 'Check-out', value: '12:00', type: 'checkout' });
        if (property.pixKey) {
          essentialsItems.push({ label: 'PIX para Pagamento', value: property.pixKey, type: 'pix' });
        }

        guideSections.push({ type: 'essentials', title: 'Essenciais', items: essentialsItems });

        // Policies as Rules
        if (policies.length > 0) {
          guideSections.push({ type: 'rules', title: 'Regras e Políticas', items: policies.map(p => ({ label: p.question, answer: p.answer })) });
        }

        // Amenities
        if (amenities.length > 0) {
          guideSections.push({ type: 'amenities', title: 'Serviços e Amenidades', items: amenities.map(a => ({ label: a.question, answer: a.answer })) });
        }

        // FAQ
        guideSections.push({ type: 'faq', title: 'Perguntas Frequentes', items: policies.slice(0, 5).map(p => ({ label: p.question, answer: p.answer })) });
      }

      // Generate unique slug
      const slug = await generateSlug(slugBase, tenantId);
      const guideUrl = `https://seuzella.com/guide/${slug}`;

      // Create guide
      const guide = await db.guestGuide.create({
        data: {
          tenantId,
          airbPropertyId: airbPropertyId || null,
          propertyId: propertyId || null,
          slug,
          title: guideTitle,
          welcomeMessage: welcomeMessage || 'Seja bem-vindo! Preparei este guia com tudo que você precisa para aproveitar sua estadia.',
          sections: JSON.stringify(guideSections),
          status: 'active',
          autoGenerated: true,
          generatedAt: new Date(),
          qrCodeUrl: guideUrl,
        },
      });

      return NextResponse.json({ success: true, guide, guideUrl, qrCodeUrl: guideUrl });
    }

    // Manual creation
    const slug = await generateSlug(title?.toLowerCase().replace(/[^a-z0-9]+/g, '-')?.slice(0, 40) || 'guia', tenantId);
    const guideUrl = `https://seuzella.com/guide/${slug}`;

    const guide = await db.guestGuide.create({
      data: {
        tenantId,
        airbPropertyId: airbPropertyId || null,
        propertyId: propertyId || null,
        slug,
        title: title || 'Guia do Hóspede',
        welcomeMessage: welcomeMessage || '',
        sections: JSON.stringify(sections || []),
        status: 'draft',
        autoGenerated: false,
        qrCodeUrl: guideUrl,
      },
    });

    return NextResponse.json({ success: true, guide, guideUrl });
  } catch (error) {
    console.error('[GuestGuide] POST error:', error);
    return NextResponse.json({ success: false, error: 'Internal server error' }, { status: 500 });
  }
}

// PUT /api/ddc/guest-guide — Update guide
async function putHandler(request: NextRequest) {
  try {
    const authenticatedTenantId = await resolveTenantId();
    if (!authenticatedTenantId) {
      return NextResponse.json({ success: false, error: 'Não autorizado' }, { status: 401 });
    }

    const body = await request.json();
    const { guideId, title, welcomeMessage, sections, status } = body;

    if (!guideId) {
      return NextResponse.json({ success: false, error: 'guideId required' }, { status: 400 });
    }

    const existing = await db.guestGuide.findFirst({
      where: { id: guideId, tenantId: authenticatedTenantId },
    });
    if (!existing) {
      return NextResponse.json({ success: false, error: 'Guide not found or not owned by tenant' }, { status: 404 });
    }

    const guide = await db.guestGuide.update({
      where: { id: existing.id },
      data: {
        title: title || undefined,
        welcomeMessage: welcomeMessage || undefined,
        sections: sections ? JSON.stringify(sections) : undefined,
        status: status || undefined,
      },
    });

    return NextResponse.json({ success: true, guide });
  } catch (error) {
    console.error('[GuestGuide] PUT error:', error);
    return NextResponse.json({ success: false, error: 'Internal server error' }, { status: 500 });
  }
}

// DELETE /api/ddc/guest-guide — Delete guide
async function deleteHandler(request: NextRequest) {
  try {
    const authenticatedTenantId = await resolveTenantId();
    if (!authenticatedTenantId) {
      return NextResponse.json({ success: false, error: 'Não autorizado' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const guideId = searchParams.get('guideId');

    if (!guideId) {
      return NextResponse.json({ success: false, error: 'guideId required' }, { status: 400 });
    }

    // Verify ownership
    const guide = await db.guestGuide.findFirst({ where: { id: guideId, tenantId: authenticatedTenantId } });
    if (!guide) {
      return NextResponse.json({ success: false, error: 'Guide not found or not owned by tenant' }, { status: 404 });
    }

    await db.guestGuide.delete({ where: { id: guide.id } });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('[GuestGuide] DELETE error:', error);
    return NextResponse.json({ success: false, error: 'Internal server error' }, { status: 500 });
  }
}

export const GET = withSecurity(getHandler, { routeLabel: 'guest-guide' });
export const POST = withSecurity(postHandler, { routeLabel: 'guest-guide' });
export const PUT = withSecurity(putHandler, { routeLabel: 'guest-guide' });
export const DELETE = withSecurity(deleteHandler, { routeLabel: 'guest-guide' });
