'use client';

import { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Card,
  CardContent,
} from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import {
  BookOpen,
  QrCode,
  Sparkles,
  Eye,
  Clock,
  Trash2,
  ExternalLink,
  Loader2,
  MoreVertical,
  Copy,
  Check,
  MapPin,
  Wifi,
  ShieldCheck,
  Plus,
  FileText,
  RefreshCw,
} from 'lucide-react';
import { toast } from 'sonner';
import { NICHE_THEME } from './DDCShell';
import type { NicheType } from '@/contexts/NicheContext';

// ═══════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════

type GuideStatus = 'active' | 'draft' | 'archived';

interface GuestGuide {
  id: string;
  slug: string;
  title: string;
  welcomeMessage: string;
  status: GuideStatus;
  viewCount: number;
  lastViewedAt: string | null;
  qrCodeUrl: string;
  autoGenerated: boolean;
  sections: string; // JSON string from DB
  createdAt?: string;
  updatedAt?: string;
}

interface GuideStats {
  totalGuides: number;
  activeGuides: number;
  totalViews: number;
  autoGenerated?: number;
}

interface GuestGuidePanelProps {
  niche: NicheType;
  tenantId?: string;
  propertyName?: string;
}

// ═══════════════════════════════════════════════════════════════
// STATUS CONFIG — Maps guide status to visual style
// ═══════════════════════════════════════════════════════════════

const STATUS_CONFIG: Record<GuideStatus, {
  label: string;
  textColor: string;
  bgColor: string;
  borderColor: string;
  icon: typeof ShieldCheck;
}> = {
  active: {
    label: 'Ativo',
    textColor: 'text-emerald-400',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/20',
    icon: ShieldCheck,
  },
  draft: {
    label: 'Rascunho',
    textColor: 'text-yellow-400',
    bgColor: 'bg-yellow-500/10',
    borderColor: 'border-yellow-500/20',
    icon: FileText,
  },
  archived: {
    label: 'Arquivado',
    textColor: 'text-zinc-400',
    bgColor: 'bg-zinc-500/10',
    borderColor: 'border-zinc-500/20',
    icon: FileText,
  },
};

// ═══════════════════════════════════════════════════════════════
// GUEST GUIDE PANEL — Main Component
// ═══════════════════════════════════════════════════════════════

export function GuestGuidePanel({ niche, tenantId, propertyName }: GuestGuidePanelProps) {
  const theme = NICHE_THEME[niche];
  const accentColor = niche === 'pousada' ? 'emerald' : 'blue';

  // State
  const [guides, setGuides] = useState<GuestGuide[]>([]);
  const [stats, setStats] = useState<GuideStats>({ totalGuides: 0, activeGuides: 0, totalViews: 0 });
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [qrCodeUrls, setQrCodeUrls] = useState<Record<string, string>>({}); // guide.id → QR data URL
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [guideToDelete, setGuideToDelete] = useState<GuestGuide | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);
  const [copiedSlug, setCopiedSlug] = useState<string | null>(null);

  // ── Fetch Guides ──────────────────────────────────────────
  const fetchGuides = useCallback(async () => {
    if (!tenantId) {
      setIsLoading(false);
      return;
    }
    setIsLoading(true);
    try {
      const res = await fetch(`/api/ddc/guest-guide?tenantId=${tenantId}`);
      if (!res.ok) throw new Error('Failed to fetch guides');
      const data = await res.json();
      if (data.success) {
        setGuides(data.guides || []);
        setStats(data.stats || { totalGuides: 0, activeGuides: 0, totalViews: 0 });
        // Generate QR codes for all guides
        await generateQrCodes(data.guides || []);
      } else {
        toast.error('Erro ao carregar guias.');
      }
    } catch (error) {
      console.error('[GuestGuidePanel] fetch error:', error);
      toast.error('Erro ao conectar com o servidor.');
    } finally {
      setIsLoading(false);
    }
  }, [tenantId]);

  // ── Generate QR Codes ────────────────────────────────────
  const generateQrCodes = async (guideList: GuestGuide[]) => {
    const newQrUrls: Record<string, string> = {};
    for (const guide of guideList) {
      const guideUrl = `https://seuzella.com/guide/${guide.slug}`;
      newQrUrls[guide.id] = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(guideUrl)}&color=10b981&bgcolor=090d16`;
    }
    setQrCodeUrls(newQrUrls);
  };

  // ── Auto-Generate Guide ──────────────────────────────────
  const handleAutoGenerate = async () => {
    if (!tenantId) return;
    setIsGenerating(true);
    try {
      const res = await fetch('/api/ddc/guest-guide', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ autoGenerate: true, tenantId }),
      });
      if (!res.ok) throw new Error('Failed to auto-generate guide');
      const data = await res.json();
      if (data.success) {
        toast.success(data.guideUrl
          ? `Guia criado! Acesse: ${data.guideUrl}`
          : 'Guia Digital criado automaticamente!'
        );
        await fetchGuides(); // Refresh list
      } else {
        toast.error(data.error || 'Erro ao criar guia.');
      }
    } catch (error) {
      console.error('[GuestGuidePanel] auto-generate error:', error);
      toast.error('Erro ao gerar guia automaticamente.');
    } finally {
      setIsGenerating(false);
    }
  };

  // ── Delete Guide ─────────────────────────────────────────
  const handleDelete = async () => {
    if (!guideToDelete || !tenantId) return;
    setIsDeleting(true);
    try {
      const res = await fetch(`/api/ddc/guest-guide?guideId=${guideToDelete.id}&tenantId=${tenantId}`, {
        method: 'DELETE',
      });
      if (!res.ok) throw new Error('Failed to delete guide');
      const data = await res.json();
      if (data.success) {
        toast.success('Guia removido com sucesso.');
        setGuides(prev => prev.filter(g => g.id !== guideToDelete.id));
        setDeleteDialogOpen(false);
        setGuideToDelete(null);
        // Refresh stats
        await fetchGuides();
      } else {
        toast.error(data.error || 'Erro ao remover guia.');
      }
    } catch (error) {
      console.error('[GuestGuidePanel] delete error:', error);
      toast.error('Erro ao remover guia.');
    } finally {
      setIsDeleting(false);
    }
  };

  // ── Copy Guide Link ─────────────────────────────────────
  const copyGuideLink = (slug: string) => {
    const url = `https://seuzella.com/guide/${slug}`;
    navigator.clipboard.writeText(url);
    setCopiedSlug(slug);
    toast.success('Link do guia copiado!');
    setTimeout(() => setCopiedSlug(null), 2000);
  };

  // ── Format Date ──────────────────────────────────────────
  const formatDate = (dateStr: string | null) => {
    if (!dateStr) return 'Nunca';
    try {
      const date = new Date(dateStr);
      return date.toLocaleDateString('pt-BR', {
        day: '2-digit',
        month: 'short',
        year: 'numeric',
      });
    } catch {
      return dateStr;
    }
  };

  // ── Parse Sections Count ─────────────────────────────────
  const getSectionsCount = (sectionsJson: string) => {
    try {
      const sections = JSON.parse(sectionsJson);
      return Array.isArray(sections) ? sections.length : 0;
    } catch {
      return 0;
    }
  };

  // ── Init ──────────────────────────────────────────────────
  useEffect(() => {
    fetchGuides();
  }, [fetchGuides]);

  // ── Niche-specific accent helpers ─────────────────────────
  const accentBg = niche === 'pousada' ? 'bg-emerald-500/15' : 'bg-blue-500/15';
  const accentBorder = niche === 'pousada' ? 'border-emerald-500/20' : 'border-blue-500/20';
  const accentText = niche === 'pousada' ? 'text-emerald-400' : 'text-blue-400';
  const accentHover = niche === 'pousada' ? 'hover:border-emerald-500/30' : 'hover:border-blue-500/30';
  const accentBtnBg = niche === 'pousada' ? 'bg-emerald-500 hover:bg-emerald-600' : 'bg-blue-500 hover:bg-blue-600';
  const accentBtnGhost = niche === 'pousada'
    ? 'hover:bg-emerald-500/10 text-emerald-400'
    : 'hover:bg-blue-500/10 text-blue-400';

  // ═══════════════════════════════════════════════════════════════
  // RENDER — Loading State
  // ═══════════════════════════════════════════════════════════════

  if (isLoading) {
    return (
      <div className="space-y-4">
        {/* Stats skeleton */}
        <div className="grid grid-cols-3 gap-3">
          {[0, 1, 2].map(i => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.05, duration: 0.3 }}
              className="bg-[#121216] border border-white/[0.04] rounded-xl p-4"
            >
              <div className="flex items-center gap-2">
                <Loader2 className="w-4 h-4 text-white/20 animate-spin" />
                <div className="h-3 w-20 bg-white/[0.04] rounded" />
              </div>
              <div className="h-5 w-16 bg-white/[0.04] rounded mt-2" />
            </motion.div>
          ))}
        </div>
        {/* Cards skeleton */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {[0, 1, 2].map(i => (
            <div
              key={i}
              className="bg-[#121216] border border-white/[0.04] rounded-xl h-64 animate-pulse"
            />
          ))}
        </div>
      </div>
    );
  }

  // ═══════════════════════════════════════════════════════════════
  // RENDER — Empty State
  // ═══════════════════════════════════════════════════════════════

  if (guides.length === 0) {
    return (
      <div className="space-y-4">
        {/* Header with auto-generate button */}
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-base font-bold text-white tracking-tight">
              Guia Digital do Hóspede
            </h2>
            <p className="text-xs text-white/40 mt-0.5">
              Crie um guia digital com tudo que seu hóspede precisa saber
            </p>
          </div>
          <Button
            onClick={handleAutoGenerate}
            disabled={isGenerating || !tenantId}
            className={`${accentBtnBg} text-white font-bold text-xs shadow-xs`}
            size="sm"
          >
            {isGenerating ? (
              <Loader2 className="w-4 h-4 animate-spin mr-1.5" />
            ) : (
              <Sparkles className="w-4 h-4 mr-1.5" />
            )}
            {isGenerating ? 'Gerando...' : 'Gerar Guia Automaticamente'}
          </Button>
        </div>

        {/* Empty State */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.4 }}
        >
          <Card className="bg-[#121216] border border-white/[0.06] rounded-xl">
            <CardContent className="p-8 flex flex-col items-center justify-center text-center">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1, duration: 0.4 }}
                className={`w-16 h-16 rounded-2xl ${accentBg} ${accentBorder} border flex items-center justify-center mb-4`}
              >
                <BookOpen className={`w-8 h-8 ${accentText}`} />
              </motion.div>

              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2, duration: 0.4 }}
              >
                <h3 className="text-lg font-bold text-white mb-2">
                  Nenhum Guia Digital criado
                </h3>
                <p className="text-sm text-white/40 max-w-md mb-6">
                  Crie um Guia Digital para compartilhar com seus hóspedes tudo que eles
                  precisam saber — Wi-Fi, check-in, regras, dicas da região e muito mais.
                  Eles acessam pelo celular, sem instalar nada.
                </p>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3, duration: 0.4 }}
                className="flex flex-col sm:flex-row gap-3"
              >
                <Button
                  onClick={handleAutoGenerate}
                  disabled={isGenerating || !tenantId}
                  className={`${accentBtnBg} text-white font-bold shadow-xs`}
                >
                  {isGenerating ? (
                    <Loader2 className="w-4 h-4 animate-spin mr-2" />
                  ) : (
                    <Sparkles className="w-4 h-4 mr-2" />
                  )}
                  {isGenerating ? 'Gerando...' : 'Gerar Automaticamente'}
                </Button>
              </motion.div>

              {!tenantId && (
                <p className="text-[10px] text-red-400/60 mt-4">
                  tenantId não disponível — faça login para criar guias.
                </p>
              )}

              {/* Feature Preview Cards */}
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.5, duration: 0.4 }}
                className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-8 max-w-lg"
              >
                {[
                  { icon: Wifi, label: 'Wi-Fi e Essenciais', desc: 'Senha, horários, PIX' },
                  { icon: MapPin, label: 'Dicas da Região', desc: 'Restaurantes, passeios' },
                  { icon: QrCode, label: 'QR Code', desc: 'Hóspede escaneia e acessa' },
                  { icon: ShieldCheck, label: 'Regras e FAQ', desc: 'Tudo claro, sem dúvidas' },
                ].map((feature, i) => (
                  <motion.div
                    key={feature.label}
                    initial={{ opacity: 0, y: 5 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.5 + i * 0.05, duration: 0.3 }}
                    className="bg-[#0a0a0f]/50 border border-white/[0.03] rounded-lg p-3 text-center"
                  >
                    <feature.icon className={`w-4 h-4 ${accentText} mx-auto mb-1.5`} />
                    <span className="text-[10px] font-bold text-white/70 block">{feature.label}</span>
                    <span className="text-[8px] text-white/30 block mt-0.5">{feature.desc}</span>
                  </motion.div>
                ))}
              </motion.div>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    );
  }

  // ═══════════════════════════════════════════════════════════════
  // RENDER — Guides List State
  // ═══════════════════════════════════════════════════════════════

  return (
    <div className="space-y-4">
      {/* ── Header ──────────────────────────────────────────── */}
      <div className="flex items-center justify-between gap-4">
        <div className="min-w-0">
          <h2 className="text-base font-bold text-white tracking-tight">
            Guia Digital do Hóspede
          </h2>
          <p className="text-xs text-white/40 mt-0.5">
            {propertyName
              ? `Guias para ${propertyName}`
              : 'Compartilhe tudo que seu hóspede precisa saber'}
          </p>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          <Button
            variant="ghost"
            size="sm"
            onClick={fetchGuides}
            disabled={isLoading}
            className={`${accentBtnGhost} text-xs`}
          >
            <RefreshCw className={`w-3.5 h-3.5 mr-1.5 ${isLoading ? 'animate-spin' : ''}`} />
            Atualizar
          </Button>
          <Button
            onClick={handleAutoGenerate}
            disabled={isGenerating || !tenantId}
            className={`${accentBtnBg} text-white font-bold text-xs shadow-xs`}
            size="sm"
          >
            {isGenerating ? (
              <Loader2 className="w-4 h-4 animate-spin mr-1.5" />
            ) : (
              <Plus className="w-4 h-4 mr-1.5" />
            )}
            {isGenerating ? 'Gerando...' : 'Novo Guia'}
          </Button>
        </div>
      </div>

      {/* ── Stats Bar ──────────────────────────────────────── */}
      <motion.div
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3 }}
        className="grid grid-cols-3 gap-3"
      >
        {[
          {
            label: 'Total de Guias',
            value: stats.totalGuides,
            icon: BookOpen,
          },
          {
            label: 'Guias Ativos',
            value: stats.activeGuides,
            icon: ShieldCheck,
          },
          {
            label: 'Visualizações',
            value: stats.totalViews,
            icon: Eye,
          },
        ].map((stat, i) => (
          <motion.div
            key={stat.label}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.05, duration: 0.3 }}
            className="bg-[#121216] border border-white/[0.04] rounded-xl p-4"
          >
            <div className="flex items-center gap-2 mb-1">
              <stat.icon className={`w-3.5 h-3.5 ${accentText}`} />
              <span className="text-[10px] text-white/40 font-bold uppercase tracking-wider">
                {stat.label}
              </span>
            </div>
            <span className="text-lg font-extrabold text-white tracking-tight font-mono">
              {stat.value}
            </span>
          </motion.div>
        ))}
      </motion.div>

      {/* ── Guide Cards Grid ──────────────────────────────── */}
      <div className="max-h-[600px] overflow-y-auto pr-1 space-y-0"
        style={{
          scrollbarWidth: 'thin',
          scrollbarColor: 'rgba(255,255,255,0.08) transparent',
        }}
      >
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <AnimatePresence mode="popLayout">
            {guides.map((guide, index) => {
              const statusCfg = STATUS_CONFIG[guide.status] || STATUS_CONFIG.draft;
              const StatusIcon = statusCfg.icon;
              const guideUrl = `https://seuzella.com/guide/${guide.slug}`;
              const qrDataUrl = qrCodeUrls[guide.id];
              const sectionsCount = getSectionsCount(guide.sections);
              const isCopied = copiedSlug === guide.slug;

              return (
                <motion.div
                  key={guide.id}
                  layout
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.9 }}
                  transition={{ delay: index * 0.04, duration: 0.3 }}
                >
                  <Card className={`bg-[#121216] border border-white/[0.04] rounded-xl overflow-hidden transition-all duration-200 ${accentHover}`}>
                    <CardContent className="p-4 space-y-3">
                      {/* ── Card Header: Title + Status ─── */}
                      <div className="flex items-start justify-between gap-2">
                        <div className="min-w-0 flex-1">
                          <div className="flex items-center gap-2 mb-1">
                            <h3 className="text-sm font-bold text-white truncate">
                              {guide.title}
                            </h3>
                            {guide.autoGenerated && (
                              <Badge
                                variant="outline"
                                className={`text-[8px] px-1 py-0 h-3.5 shrink-0 ${accentBorder} ${accentText} ${accentBg}`}
                              >
                                Auto
                              </Badge>
                            )}
                          </div>
                          {/* Status Badge */}
                          <Badge
                            variant="outline"
                            className={`text-[9px] px-1.5 py-0 h-4 shrink-0 ${statusCfg.borderColor} ${statusCfg.textColor} ${statusCfg.bgColor}`}
                          >
                            <StatusIcon className="w-2.5 h-2.5 mr-0.5" />
                            {statusCfg.label}
                          </Badge>
                        </div>
                        {/* Actions Menu */}
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <Button
                              variant="ghost"
                              size="icon"
                              className="w-7 h-7 p-0 hover:bg-white/[0.04] text-white/40 hover:text-white/70 shrink-0"
                            >
                              <MoreVertical className="w-4 h-4" />
                            </Button>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent
                            align="end"
                            className="w-40 bg-[#0a0a0f] border-white/[0.06]"
                          >
                            <DropdownMenuItem
                              className="text-white/70 hover:text-white hover:bg-white/[0.04] cursor-pointer"
                              onClick={() => copyGuideLink(guide.slug)}
                            >
                              {isCopied ? (
                                <Check className="w-4 h-4 mr-2 text-emerald-400" />
                              ) : (
                                <Copy className="w-4 h-4 mr-2" />
                              )}
                              {isCopied ? 'Copiado!' : 'Copiar Link'}
                            </DropdownMenuItem>
                            <DropdownMenuItem
                              className="text-white/70 hover:text-white hover:bg-white/[0.04] cursor-pointer"
                              onClick={() => window.open(guideUrl, '_blank')}
                            >
                              <ExternalLink className="w-4 h-4 mr-2" />
                              Abrir Guia
                            </DropdownMenuItem>
                            <DropdownMenuItem
                              className="text-red-400 hover:text-red-300 hover:bg-red-500/10 cursor-pointer"
                              onClick={() => {
                                setGuideToDelete(guide);
                                setDeleteDialogOpen(true);
                              }}
                            >
                              <Trash2 className="w-4 h-4 mr-2" />
                              Remover Guia
                            </DropdownMenuItem>
                          </DropdownMenuContent>
                        </DropdownMenu>
                      </div>

                      {/* ── Welcome Message Preview ─── */}
                      {guide.welcomeMessage && (
                        <p className="text-[11px] text-white/40 leading-relaxed line-clamp-2">
                          {guide.welcomeMessage}
                        </p>
                      )}

                      {/* ── QR Code Display ─── */}
                      {qrDataUrl && (
                        <div className="flex items-center gap-3">
                          <div className={`w-24 h-24 rounded-lg ${accentBg} ${accentBorder} border flex items-center justify-center p-1.5`}>
                            <img
                              src={qrDataUrl}
                              alt={`QR Code para ${guide.title}`}
                              className="w-full h-full object-contain rounded"
                            />
                          </div>
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-1 mb-1">
                              <QrCode className={`w-3.5 h-3.5 ${accentText}`} />
                              <span className="text-[10px] text-white/40 font-bold uppercase tracking-wider">
                                QR Code
                              </span>
                            </div>
                            <p className="text-[9px] text-white/30 font-mono truncate">
                              {guideUrl}
                            </p>
                            <button
                              onClick={() => copyGuideLink(guide.slug)}
                              className={`text-[10px] ${accentText} font-semibold mt-1 hover:underline cursor-pointer inline-flex items-center gap-0.5`}
                            >
                              <Copy className="w-2.5 h-2.5" />
                              Copiar link
                            </button>
                          </div>
                        </div>
                      )}

                      {/* ── Guide Stats ─── */}
                      <div className="grid grid-cols-3 gap-2 pt-2 border-t border-white/[0.03]">
                        <div className="text-center">
                          <Eye className={`w-3 h-3 ${accentText} mx-auto mb-0.5`} />
                          <span className="text-xs font-bold text-white font-mono">
                            {guide.viewCount}
                          </span>
                          <span className="text-[8px] text-white/30 block">Views</span>
                        </div>
                        <div className="text-center">
                          <Clock className="w-3 h-3 text-white/30 mx-auto mb-0.5" />
                          <span className="text-[9px] text-white/50 font-mono">
                            {formatDate(guide.lastViewedAt)}
                          </span>
                          <span className="text-[8px] text-white/30 block">Último acesso</span>
                        </div>
                        <div className="text-center">
                          <BookOpen className="w-3 h-3 text-white/30 mx-auto mb-0.5" />
                          <span className="text-xs font-bold text-white font-mono">
                            {sectionsCount}
                          </span>
                          <span className="text-[8px] text-white/30 block">Seções</span>
                        </div>
                      </div>

                      {/* ── Guide Link ─── */}
                      <div className={`flex items-center gap-2 rounded-lg p-2 ${accentBg} ${accentBorder} border`}>
                        <ExternalLink className={`w-3.5 h-3.5 ${accentText} shrink-0`} />
                        <a
                          href={guideUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className={`text-[10px] ${accentText} font-medium truncate hover:underline`}
                        >
                          {guideUrl}
                        </a>
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              );
            })}
          </AnimatePresence>
        </div>
      </div>

      {/* ── Delete Confirmation Dialog ────────────────────── */}
      <Dialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <DialogContent className="bg-[#0a0a0f] border border-white/[0.08] text-white max-w-md p-6 rounded-xl shadow-2xl">
          <DialogHeader className="border-b border-white/[0.04] pb-4">
            <DialogTitle className="text-base font-extrabold text-white flex items-center gap-2">
              <span className="p-1.5 rounded-lg bg-red-500/10 text-red-400 border border-red-500/20">
                <Trash2 className="w-4 h-4" />
              </span>
              Remover Guia Digital
            </DialogTitle>
            <DialogDescription className="text-zinc-500 text-xs mt-1">
              Tem certeza que deseja remover este guia? Esta ação não pode ser revertida.
              Hóspedes com o link não conseguirão acessar o conteúdo.
            </DialogDescription>
          </DialogHeader>

          {guideToDelete && (
            <div className="pt-4 space-y-3">
              {/* Guide summary */}
              <div className="bg-[#121216] border border-white/[0.04] rounded-lg p-3">
                <div className="flex items-center gap-2 mb-1">
                  <BookOpen className={`w-4 h-4 ${accentText}`} />
                  <span className="text-sm font-bold text-white truncate">
                    {guideToDelete.title}
                  </span>
                </div>
                <div className="flex items-center gap-2 text-[10px] text-white/40">
                  <Eye className="w-3 h-3" />
                  <span>{guideToDelete.viewCount} visualizações</span>
                </div>
              </div>

              {/* Actions */}
              <div className="flex items-center justify-end gap-2 pt-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setDeleteDialogOpen(false)}
                  className="text-white/60 hover:text-white hover:bg-white/[0.04] text-xs"
                  disabled={isDeleting}
                >
                  Cancelar
                </Button>
                <Button
                  variant="destructive"
                  size="sm"
                  onClick={handleDelete}
                  disabled={isDeleting}
                  className="bg-red-500 hover:bg-red-600 text-white font-bold text-xs"
                >
                  {isDeleting ? (
                    <Loader2 className="w-4 h-4 animate-spin mr-1.5" />
                  ) : (
                    <Trash2 className="w-4 h-4 mr-1.5" />
                  )}
                  {isDeleting ? 'Removendo...' : 'Remover Guia'}
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
