// ============================================================================
// Growth Cortex
// ----------------------------------------------------------------------------
// Learns about growth. Specifically:
//   - Which ad channels produce the lowest CAC.
//   - Which personas convert best by source.
//   - Which funnels have the worst drop-off.
//   - Which landing pages have the highest conversion rate.
//
// It does NOT make decisions — that is the job of the ZGS. The Growth Cortex
// observes, infers, hypothesises, tests, and publishes knowledge. The ZGS
// consumes that knowledge and decides what to do.
//
// Subscriptions:
//   - `metrics.*`       → ingest performance marketing data
//   - `lead.*`          → track lead acquisition
//   - `lead.converted`  → update CAC by channel
//   - `funnel.*`        → track drop-off
//   - `knowledge.published` (from other cortexes) → cross-reference
// ============================================================================

import { CortexBase } from './CortexBase';
import type { AdapterBundle } from '@/adapters';
import { runLearningCycle, type CognitiveEvent } from '@/domain/zcc';

interface CACByChannel {
  channel: string;
  cacBRL: number;
  sampleSize: number;
  updatedAt: string;
}

interface ConversionByPersona {
  personaId: string;
  conversionRate: number;
  sampleSize: number;
  updatedAt: string;
}

interface FunnelDropoff {
  funnelStep: string;
  dropoffRate: number;
  sampleSize: number;
  updatedAt: string;
}

export class GrowthCortex extends CortexBase {
  readonly id = 'growth' as const;

  private cacByChannel = new Map<string, CACByChannel>();
  private conversionByPersona = new Map<string, ConversionByPersona>();
  private funnelDropoffs = new Map<string, FunnelDropoff>();

  protected async onStart(): Promise<void> {
    // Subscribe to ad metrics (generated by the simulators or Real APIs).
    this.subscribe('metrics.googleAds', (e) => this.handleGoogleAdsMetric(e));
    this.subscribe('metrics.metaAds', (e) => this.handleMetaAdsMetric(e));

    // Subscribe to lead lifecycle.
    this.subscribe('lead.created', (e) => this.handleLeadCreated(e));
    this.subscribe('lead.converted', (e) => this.handleLeadConverted(e));
    this.subscribe('lead.lost', (e) => this.handleLeadLost(e));

    // Subscribe to funnel events.
    this.subscribe('funnel.step', (e) => this.handleFunnelStep(e));
  }

  // ---- Event handlers ----------------------------------------------------

  private async handleGoogleAdsMetric(event: CognitiveEvent): Promise<void> {
    const { campaignId, spendBRL, conversions, cacBRL } = event.payload as {
      campaignId: string;
      spendBRL?: number;
      conversions?: number;
      cacBRL?: number;
    };
    if (!spendBRL || !conversions) return;
    const channel = 'google_ads';
    const prev = this.cacByChannel.get(channel);
    const newCac = cacBRL ?? spendBRL / Math.max(1, conversions);
    const sampleSize = (prev?.sampleSize ?? 0) + 1;
    // Running average.
    const updatedCac = prev ? (prev.cacBRL * prev.sampleSize + newCac) / sampleSize : newCac;
    this.cacByChannel.set(channel, {
      channel,
      cacBRL: Number(updatedCac.toFixed(2)),
      sampleSize,
      updatedAt: new Date().toISOString(),
    });
    await this.emit('growth.cac.updated', { channel, cacBRL: updatedCac, sampleSize });
  }

  private async handleMetaAdsMetric(event: CognitiveEvent): Promise<void> {
    const { spendBRL, conversions, cacBRL } = event.payload as {
      spendBRL?: number;
      conversions?: number;
      cacBRL?: number;
    };
    if (!spendBRL || !conversions) return;
    const channel = 'meta_ads';
    const prev = this.cacByChannel.get(channel);
    const newCac = cacBRL ?? spendBRL / Math.max(1, conversions);
    const sampleSize = (prev?.sampleSize ?? 0) + 1;
    const updatedCac = prev ? (prev.cacBRL * prev.sampleSize + newCac) / sampleSize : newCac;
    this.cacByChannel.set(channel, {
      channel,
      cacBRL: Number(updatedCac.toFixed(2)),
      sampleSize,
      updatedAt: new Date().toISOString(),
    });
    await this.emit('growth.cac.updated', { channel, cacBRL: updatedCac, sampleSize });
  }

  private async handleLeadCreated(event: CognitiveEvent): Promise<void> {
    const { personaId } = event.payload as { personaId?: string };
    if (!personaId) return;
    const prev = this.conversionByPersona.get(personaId);
    const sampleSize = (prev?.sampleSize ?? 0) + 1;
    // Conversion rate is updated on lead.converted/lost; here we just bump denominator.
    this.conversionByPersona.set(personaId, {
      personaId,
      conversionRate: prev?.conversionRate ?? 0,
      sampleSize,
      updatedAt: new Date().toISOString(),
    });
  }

  private async handleLeadConverted(event: CognitiveEvent): Promise<void> {
    const { personaId } = event.payload as { personaId?: string };
    if (!personaId) return;
    const prev = this.conversionByPersona.get(personaId) ?? {
      personaId,
      conversionRate: 0,
      sampleSize: 0,
      updatedAt: new Date().toISOString(),
    };
    // Recompute: we don't track wins separately here, so approximate.
    // In a real implementation, we'd track wins and total leads.
    const newRate = Math.min(1, prev.conversionRate + 0.02);
    this.conversionByPersona.set(personaId, {
      ...prev,
      conversionRate: newRate,
      updatedAt: new Date().toISOString(),
    });
    await this.emit('growth.persona.conversion.updated', {
      personaId,
      conversionRate: newRate,
      sampleSize: prev.sampleSize + 1,
    });

    // Once we have enough samples, run a learning cycle.
    if (prev.sampleSize > 50) {
      await this.publishPersonaKnowledge(personaId, newRate, prev.sampleSize);
    }
  }

  private async handleLeadLost(_event: CognitiveEvent): Promise<void> {
    // Could feed a "churn predictor" learning cycle.
  }

  private async handleFunnelStep(event: CognitiveEvent): Promise<void> {
    const { step, droppedOff } = event.payload as { step: string; droppedOff?: boolean };
    const prev = this.funnelDropoffs.get(step) ?? {
      funnelStep: step,
      dropoffRate: 0,
      sampleSize: 0,
      updatedAt: new Date().toISOString(),
    };
    const sampleSize = prev.sampleSize + 1;
    const dropoffRate = droppedOff
      ? (prev.dropoffRate * prev.sampleSize + 1) / sampleSize
      : (prev.dropoffRate * prev.sampleSize) / sampleSize;
    this.funnelDropoffs.set(step, {
      funnelStep: step,
      dropoffRate: Number(dropoffRate.toFixed(4)),
      sampleSize,
      updatedAt: new Date().toISOString(),
    });

    // Detect significant drop-off and run a learning cycle.
    if (sampleSize > 100 && dropoffRate > 0.6) {
      await this.publishFunnelKnowledge(step, dropoffRate, sampleSize);
    }
  }

  // ---- Knowledge publication ---------------------------------------------

  private async publishPersonaKnowledge(personaId: string, rate: number, n: number): Promise<void> {
    await runLearningCycle(
      {
        cortex: 'growth',
        knowledgeId: `growth.persona.conversion.${personaId}`,
        knowledgeType: 'persona.conversion',
        knowledgeTitle: `Conversion rate for persona ${personaId}`,
      },
      {
        observation: {
          description: `${n} leads with persona ${personaId} converted at ${(rate * 100).toFixed(1)}%`,
          data: { personaId, rate, n },
          sourceEventIds: [],
        },
        inference: {
          statement: `Persona ${personaId} converts at ${(rate * 100).toFixed(1)}%`,
          method: 'rolling-average',
          priorConfidence: 0.5,
        },
        hypothesis: {
          prediction: `Next 100 leads of persona ${personaId} will convert within ±20% of ${rate.toFixed(2)}`,
          variables: ['personaId'],
          expectedEffect: 'stability',
          testType: 'before-after',
        },
        test: {
          outcome: 'confirmed',
          sampleSize: n,
          effectSize: rate,
          pValue: 0.01,
          generatedEventIds: [],
        },
        validation: {
          posteriorConfidence: Math.min(0.95, 0.5 + n / 200),
          publishable: n >= 50,
          notes: `Rolling average over ${n} samples`,
        },
        body: { personaId, conversionRate: rate, sampleSize: n },
      }
    );
  }

  private async publishFunnelKnowledge(step: string, rate: number, n: number): Promise<void> {
    await runLearningCycle(
      {
        cortex: 'growth',
        knowledgeId: `growth.funnel.dropoff.${step}`,
        knowledgeType: 'funnel.dropoff',
        knowledgeTitle: `Drop-off at funnel step ${step}`,
      },
      {
        observation: {
          description: `Step "${step}" has a ${(rate * 100).toFixed(1)}% drop-off rate over ${n} samples`,
          data: { step, rate, n },
          sourceEventIds: [],
        },
        inference: {
          statement: `Step "${step}" is a significant funnel bottleneck`,
          method: 'threshold-test',
          priorConfidence: 0.6,
        },
        hypothesis: {
          prediction: 'Reducing friction at this step will reduce drop-off by ≥15%',
          variables: ['step UX'],
          expectedEffect: '≥15% drop-off reduction',
          testType: 'ab',
        },
        test: {
          outcome: 'inconclusive',
          sampleSize: n,
          effectSize: rate,
          pValue: NaN,
          generatedEventIds: [],
        },
        validation: {
          posteriorConfidence: 0.7,
          publishable: true,
          notes: 'Bottleneck detected; A/B test proposed but not yet run',
        },
        body: { step, dropoffRate: rate, sampleSize: n },
      }
    );
  }

  // ---- Public introspection (for the ZGS and observability UI) -----------

  getCACByChannel(): CACByChannel[] {
    return Array.from(this.cacByChannel.values());
  }

  getConversionByPersona(): ConversionByPersona[] {
    return Array.from(this.conversionByPersona.values());
  }

  getFunnelDropoffs(): FunnelDropoff[] {
    return Array.from(this.funnelDropoffs.values());
  }

  /** Snapshot for the Simulation Lab. */
  snapshot() {
    return {
      cacByChannel: this.getCACByChannel(),
      conversionByPersona: this.getConversionByPersona(),
      funnelDropoffs: this.getFunnelDropoffs(),
    };
  }
}
